Added persistent sessions to 'How to run ACCESS-CM' page
ACCESS-NRI/access-hive.org.au pull request #649
Opened 2024-01-30 02:53 UTC by atteggiani

Updated 'How to run ACCESS-CM' page with the new persistent session workflow.\nAlso added some instructions to try and port a suite from accessdev to persistent sessions.

2024-01-30 03:08 UTC, atteggiani commented
@MartinDix 
For the review, the main sections that changed are:
[Setup ACCESS-CM persistent session](https://access-hive.org.au/pr-preview/pr-649/models/run-a-model/run-access-cm/#setup-access-cm-persistent-session) and [Port suites from accessdev](https://access-hive.org.au/pr-preview/pr-649/models/run-a-model/run-access-cm/#port-suites-from-accessdev)

2024-01-30 10:00 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +To support the use of long-running processes (such as ACCESS models runs), NCI provides a service on <i>Gadi</i> called <a href="https://opus.nci.org.au/display/Help/Persistent+Sessions" target="_bla
Edit: “To support the use of long-running processes, such as ACCESS model runs, ..."

2024-01-30 10:06 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +    The project assigned to a persistent session does not have to be necessarily the same to the project used to run {{ model }} configuration, but needs to have allocated <i>Service Units</i> (SU).
Edit: "While the project assigned to a persistent session does not have to be the same as the project used to run the {{ model }} configuration, it does need to have allocated <i>Service Units</i> (SU)."

2024-01-30 10:08 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +To list all the active persistent sessions run:
Edit “To list all active persistent sessions, run:"

2024-01-30 10:11 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +The full name of a newly created persistent session is formatted as:
Edit: “The name of a newly-created persistent session has the following format:"

2024-01-30 10:18 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +For example, if the user <code>dm5220</code> started a persistent session named <code>cylc</code>, under the project <code>tm70</code>, the command will be:
Is ‘dm5220' your gadi username? I would use something more generic like ‘ab1234'

2024-01-30 10:22 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +For more information on how to specify the target session, check <a href="https://opus.nci.org.au/display/DAE/Run+Cylc7+Suites#RunCylc7Suites-SpecifyTargetSession" target="_blank">Specify Target Sess
Edit: “target="_blank">Specify Target Session with Cylc7 Suites</a>."

2024-01-30 10:26 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +    You can concurrently submit multiple {{ model }} runs using the same persistent session, without the need to start another one. Therefore, the process of specifying the target persistent session
Edit: “ You can simultaneously submit multiple {{ model }} runs using the same persistent session without needing to start a new one. Hence, the process of specifying the target persistent session for {{ model }} should only need to be done once."

2024-01-30 10:28 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +        Make sure to load a version of <i>Cylc</i> >= <code>23.09</code>, as earlier versions do not support the persistent sessions workflow.
Edit: “Make sure to load a version of <i>Cylc</i> >= <code>23.09</code> as earlier versions do not support the persistent session workflow."

2024-01-30 10:30 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +        Also, before loading the <i>Cylc</i> module, make sure to have started a persistent session and to have assigned it to the {{ model }} workflow. For more information about these steps, check
Edit: "Also, before loading the <i>Cylc</i> module, make sure you have started a persistent session and assigned it to the {{ model }} workflow…"

2024-01-30 10:34 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +If you have a suite that was running on <i>accessdev</i>, you can run it on persistent sessions by doing the following steps:
Edit: ”If you have a suite that was running on <i>accessdev</i>, you can run it using persistent sessions by carrying out the following steps:"

2024-01-30 10:36 UTC, heidinett requested changes
Looks good Davide! 
I made only some minor edit suggestions where applicable.

2024-01-30 22:33 UTC, atteggiani commented on docs/models/run-a-model/run-access-cm.md
> +The full name of a newly created persistent session is formatted as:
I say "full name" to distinguish it from the persistent session `name` mentioned before.

2024-01-30 22:37 UTC, atteggiani commented on docs/models/run-a-model/run-access-cm.md
> +The easiest way to do so, is to insert the persistent session full name into the file <code>~/.persistent-sessions/cylc-session</code>.
Same thing here, changed "name" with "label".

2024-02-12 03:22 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +    If you are an <i>accessdev</i> user, make sure you are a member of <a href="https://my.nci.org.au/mancini/project/hr22/join" target="_blank">hr22</a> and <a href="https://my.nci.org.au/mancini/pr
Edit: "If you are an accessdev user, make sure you are a member of hr22 and ki32 projects. Then, refer to instructions on {how to Setup ACCESS-CM persistent session} and how to {Port suites from accessdev}."

2024-02-12 03:26 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +        To run {{ model }}, it is preferred to start an <a href="https://are.nci.org.au/pun/sys/dashboard/batch_connect/sys/desktop_vnc/ncigadi/session_contexts/new" target="_blank">Australian Resear
Edit: “To run ACCESS-CM, start an [Australian Research Environment (ARE) VDI Desktop session."

2024-02-12 03:27 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +## Setup ARE VDI Desktop (optional)
Edit: "Setup an ARE VDI Desktop (optional)"

2024-02-12 03:32 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +To skip this step and run {{ model }} from <i>Gadi</i> login node instead, check <a href="{{ '#setup-%s-persistent-session'%model.lower() }}">Setup {{ model }} persistent session</a>.
Edit: "To skip this step and instead run ACCESS-CM from a Gadi login node, refer to instructions on how to [Setup an ACCESS-CM persistent session]."

2024-02-12 03:37 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +Go to the <a href="https://are.nci.org.au/pun/sys/dashboard/batch_connect/sys/desktop_vnc/ncigadi/session_contexts/new" target="_blank">ARE VDI</a> page and launch a session with the following direct
Edit: replace “directives” with “entries"

2024-02-12 03:41 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +        As said above, the ARE VDI session is only needed for setup and startup tasks, which can be easily done with only 1 CPU.
Edit: replace “said” with “mentioned”, replace “done with “accomplished” and remove “only” (already used only is the sentence)

2024-02-12 03:45 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +To support the use of long-running processes, such as ACCESS models runs, NCI provides a service on <i>Gadi</i> called <a href="https://opus.nci.org.au/display/Help/Persistent+Sessions" target="_blan
Edit: replace “models” with “model"

2024-02-12 03:46 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +<pre><code>persistent-sessions start &lt;name&gt;</code></pre>
Edit: “To start a new persistent session on Gadi, using either a login node or an ARE terminal instance, run the following command:"

2024-02-12 03:53 UTC, atteggiani commented
Thank you @heidinett 
Updated edits. 

Merging now.

2024-02-12 04:10 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +This will start a persistent session with the given <code>name</code> that runs under your <a href="/getting_started/first_steps#change-default-project-on-gadi">default project</a>.
Edit: replace “the given name” with “a given name"

2024-02-12 04:13 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +The easiest way to do this, is to insert the persistent session label into the file <code>~/.persistent-sessions/cylc-session</code>.
Edit: remove comma "The easiest way to do this is to…"

2024-02-12 04:14 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +For example, if the user <code>abc123</code> started a persistent session named <code>cylc</code>, under the project <code>xy00</code>, the command will be:
Edit: remove comma “… a persistent session named cylc under the project…"

2024-02-12 04:14 UTC, atteggiani commented on docs/models/run-a-model/run-access-cm.md
> +This will start a persistent session with the given <code>name</code> that runs under your <a href="/getting_started/first_steps#change-default-project-on-gadi">default project</a>.
Why "a" given name?
That's the specific `name` it was used in the command, I think in this case is correct "the" given name.

2024-02-12 04:15 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +For more information on how to specify the target session, check <a href="https://opus.nci.org.au/display/DAE/Run+Cylc7+Suites#RunCylc7Suites-SpecifyTargetSession" target="_blank">Specify Target Sess
Edit: replace “check” with “read”.

2024-02-12 04:17 UTC, atteggiani commented on docs/models/run-a-model/run-access-cm.md
> +For more information on how to specify the target session, check <a href="https://opus.nci.org.au/display/DAE/Run+Cylc7+Suites#RunCylc7Suites-SpecifyTargetSession" target="_blank">Specify Target Sess
I will replace it with "refer to"

2024-02-12 04:19 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +    After specifying the {{ model }} target persistent session the first time, to run {{ model }} you just have to make sure to have an active persistent session named like the {{ model }} target per
Edit: “... the first time, to run {{ model }} you just need to make sure that you have an active persistent session…"

2024-02-12 04:23 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +For this example you can use <code>u-cy339</code>, which is a preindustrial experiment suite.
Edit: replace “preindustrial” with “pre-industrial” (I prefer the hyphen, but I can be overruled)

2024-02-12 04:28 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +        Make sure to load a version of <i>Cylc</i> >= <code>23.09</code> as earlier versions do not support the persistent sessions workflow.
Edit: "Make sure to load a Cylc version of 23.09 (or later) as earlier versions…"

2024-02-12 04:29 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +        Also, before loading the <i>Cylc</i> module, make sure to have started a persistent session and assigned it to the {{ model }} workflow. For more information about these steps, check <a href=
I would replace “check” with either “see” or “read"

2024-02-12 04:37 UTC, atteggiani commented on docs/models/run-a-model/run-access-cm.md
> +        Also, before loading the <i>Cylc</i> module, make sure to have started a persistent session and assigned it to the {{ model }} workflow. For more information about these steps, check <a href=
Replacing with "refer to"

2024-02-12 05:25 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +        To create the needed SSH keys, run the following command:
replace “needed” with “required” (already used “need” in this sentence)

2024-02-12 05:27 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +        You can manually set all occurrencies of <code>host</code> to <code>localhost</code> in the suite configuration files.
replace “occurrencies” with “occurrences”.

2024-02-12 05:32 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +        Therefore, the respective folders need to be added to the <code>storage</code> directive in the suite configuration files.
Combine above two sentences: “As the persistent session workflow uses files in the hr22 and ki32 project folders on Gadi, the respective folders need to be added to the storage directive in the suite configuration files."

2024-02-12 05:32 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +        You can do this manually, or run the following command in the suite folder:
Edit: “… or run the following command from within the suite directory:"

2024-02-12 05:34 UTC, heidinett approved these changes
Looks good Davide! I left a few suggested edits. Feel free to accept or reject these.

2024-02-12 05:36 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +This will start a persistent session with the given <code>name</code> that runs under your <a href="/getting_started/first_steps#change-default-project-on-gadi">default project</a>.
ok, I agree with “the”.

2024-02-12 05:40 UTC, atteggiani commented
Thank you @heidinett. 

Merging now.

2024-02-12 05:40 UTC, merged