Flick/tutorials update
ACCESS-NRI/access-hive.org.au pull request #664
Opened 2024-04-09 06:46 UTC by flicj191

## Description

Adding links to additional videos to the tutorials tab for ESMValTool and ILAMB

## Type of change

-  New link / content

## Checklist:

- [ ] The new content is accessible and located in the appropriate section
- [ ] I have checked that the links are valid and point to the intended content

2024-04-09 23:56 UTC, atteggiani requested changes
Thank you @flicj191
Just minor comments/reviews about naming of Youtube Videos

2024-04-09 23:56 UTC, atteggiani commented on docs/tutorials/esmvaltool.md
> +## 2023/24 Video series
```suggestion
## YouTube Video Series
```

I personally would not 'bind' the videos to a year. 
I would rather call the video `YouTube Video Series` in general.

2024-04-09 23:56 UTC, atteggiani commented on docs/tutorials/ilamb.md
> +## 2024 Videos
```suggestion
## YouTube Video Series
```

Same as above

2024-04-10 03:53 UTC, flicj191 commented on docs/tutorials/ilamb.md
> +## 2024 Videos
Thanks!

2024-04-16 23:24 UTC, atteggiani approved these changes

2024-04-16 23:32 UTC, KAUR1984 approved these changes

2024-04-17 02:32 UTC, merged