Restyling "How to run ccess-om2" page + Markdown restyling
ACCESS-NRI/access-hive.org.au pull request #673
Opened 2024-04-22 04:42 UTC by atteggiani

The recently updated page "How to run ACCESS-OM2" had a few styling and formatting issues, that were making it not consistent with other pages in the website.

**MODIFICATIONS SPECIFIC TO THE PAGE**
- [x] Reformat "References" using HTML to have the same styling as other pages in the website;
- [x] A few rewording/additions/deletions (The structure of the page was left untouched, with "how to run" section coming before "how to modify")

**MODIFICATIONS NOT SPECIFIC TO THE PAGE**
- [x] Modified styling guidelines in the README
- [x] Changed CSS so that admonitions (`!!! ...` and `??? ...` in markdown) have the desired style.
From now on the admonitions can be used as described in the [admonition documentation](https://squidfunk.github.io/mkdocs-material/reference/admonitions/), with a few differences in the rendered style.
Therefore, markdown syntax is encouraged for readability. 
More information about styling guidelines in the README.
- [x] Other minor modifications 

I have converted everything to Markdown.
As you can see it's all Markdown, with the exception of virtual terminal windows and references (in the near future we will style references properly also in Markdown).

Feel free to comment on any wording/addition/deletion, or any other part you think needs changing.

Cheers

2024-04-22 04:57 UTC, aidanheerdegen commented
Could you rebase on `development` and force push? This contains a bunch of commits that have been merged already.

FYI, your commits aren't signed. See https://github.com/ACCESS-NRI/dev-docs/issues/23 for how to configure this.

2024-04-22 05:14 UTC, heidinett commented on README.md
> +- All types of admonitions (info, warning, etc.), collapsible and not, can be used as per [documentation](https://squidfunk.github.io/mkdocs-material/reference/admonitions/), but they are rendered sl
Edit: "... can be used as described in the [documentation]..."
Edit: "... use the HTML version of these, please refer to the HTML..."

2024-04-22 05:15 UTC, heidinett commented on docs/about/user_support/index.md
> +??? question "What is the difference between _model_, _model component_, and _model configuration_?"
Edit: remove comma before 3rd item in list: "model component_ and _model configuration_?"

2024-04-22 05:41 UTC, heidinett commented on docs/models/run-a-model/run-access-om.md
> +The `config.yaml` file located in the _control_ directory, is the _Master Configuration_ file, which controls the general model configuration.<br>
Remove comma: "... config.yaml file located in the control directory is the Master Configuration file..."

2024-04-22 05:42 UTC, heidinett commented on docs/models/run-a-model/run-access-om.md
> +If a model run is unsuccessful the `work` directory is left untouched to facilitate the identification of the cause of the model failure.
Add comma: "If a model run is unsuccessful, the `work` directory... "

2024-04-22 05:43 UTC, heidinett commented on docs/models/run-a-model/run-access-om.md
> +It contains several parts, some of which it is more likely will need modification, and others which are rarely changed without having a deep understanding of how the model is configured.
I would remove the line break before this sentence as "It" relates to the previous sentence.

2024-04-22 05:45 UTC, heidinett commented on docs/models/run-a-model/run-access-om.md
> +For example, when debugging changes to a model it is common to reduce the run length to minimise resource consumption and return faster feedback on changes.
Add comma: "... when debugging changes to a model, it is common... "

2024-04-22 05:46 UTC, heidinett commented on docs/models/run-a-model/run-access-om.md
> +    While `restart_period` can be reduced, it should not be increased to more than 5 years, to avoid errors.
Remove comma: "... more than 5 years to avoid errors."

2024-04-22 05:47 UTC, heidinett commented on docs/models/run-a-model/run-access-om.md
> +If the model has been altered and needs longer time to complete, more memory, or needs to be submitted under a different NCI project, you will need to modify the following section in the `config.yaml
Replace "longer" with "mor":  "... altered and needs more time to complete..."

2024-04-22 05:56 UTC, atteggiani commented
> Could you rebase on `development` and force push? This contains a bunch of commits that have been merged already.

Yeah that is because I initially created the branch starting from your branch that was then merged already.
I ran `git rebase development` and then force pushing the content. However, it seems there are still your merged commits.
Not sure how to solve this (other than createing a new branch from `development` and re-apply all the modifications I made on this)

2024-04-22 05:59 UTC, heidinett approved these changes
Looks great! Only suggested a few minor edits - see comments.

2024-04-22 07:42 UTC, atteggiani commented
> Could you rebase on `development` and force push? This contains a bunch of commits that have been merged already.
> 
> FYI, your commits aren't signed. See [ACCESS-NRI/dev-docs#23](https://github.com/ACCESS-NRI/dev-docs/issues/23) for how to configure this.

@aidanheerdegen 
Done! 
Thank you for pointing out about the signed commits!

2024-04-22 23:16 UTC, atteggiani commented
References also (almost entirely) written in markdown.

2024-04-24 00:05 UTC, atteggiani commented
Do we also need to change anything in the [ACCESS-OM](https://access-hive.org.au/models/configurations/access-om/) Models section after the new ACCESS-OM2 configurations release?

2024-04-24 04:43 UTC, flicj191 approved these changes
Looks great, great work!

2024-04-24 04:47 UTC, KAUR1984 approved these changes

2024-04-24 07:29 UTC, aidanheerdegen requested changes
Thanks Davide. You've picked up some errors/omissions and the modifications of the text improve readability.

Most of the suggested changes are highlighting styling inconsistencies, removing html elements or making the instructions consistent with updates in the released configs.

2024-04-24 07:29 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-om.md
>      error: resub.sh
```suggestion
   error: tools/resub.sh
```
Moved scripts to `tools` subdirectories

2024-04-25 00:34 UTC, atteggiani commented on docs/models/run-a-model/run-access-om.md
> +The _laboratory_ directory is a shared space for all *payu* experiments using the same model.<br>
*payu* (\*payu*) is not bold, is italic.
**payu** (\*\*payu**) is bold.

Anyway I changed the italic markdown syntax to underscores (\_payu_) to avoid confusion.

2024-04-25 00:36 UTC, atteggiani commented on README.md
> +- Italic needs to be used when referring to specific proper nouns (for example *Gadi* or *payu*);
payu (and Gadi) are italic here. 
Anyway, I changed the Markdown syntax for italic to undesrcore-wrapped words so it's not confused with the double-start-wrapped bold syntax.

2024-04-25 00:41 UTC, atteggiani commented on docs/models/run-a-model/run-access-om.md
>  restart_freq: 50Y
Are they required to be set as a string or you are just setting it as strings in the released configs? 
Because if the former is true, then we might need to make it clearer in the instructions.

2024-04-29 07:38 UTC, atteggiani commented
Thanks @aidanheerdegen for the review. 

I have updated the branch with your suggestions.

2024-04-30 06:12 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-om.md
>  restart_freq: 50Y
Actually I'm not sure. @jo-basevi?

2024-04-30 09:39 UTC, aidanheerdegen requested changes
Just noticed line 103 (`cd 1deg_jra55_ryf`) is missing a prompt (needs `data=input`).

I also realised there is no instructions on how to get help. A link to the user support page (https://access-hive.org.au/about/user_support/) would be appropriate.

These are the form of words I used in the release notice. I think something like this is also worth including as well as the link above:

> If you have questions about [access-om2](https://forum.access-hive.org.au/tag/access-om2) create a topic in the [COSIMA](https://forum.access-hive.org.au/c/cosima/29) category on the [ACCESS Hive Forum](https://forum.access-hive.org.au) and tag it with [access-om2](https://forum.access-hive.org.au/tag/access-om2). If you require assistance [follow the guidelines for requesting help from ACCESS-NRI ](https://forum.access-hive.org.au/t/access-help-and-support/908).

2024-04-30 23:13 UTC, jo-basevi commented on docs/models/run-a-model/run-access-om.md
>  restart_freq: 50Y
The quotes are not needed as it will still be read as a string when loading the yaml file. `Y` is not a supported time unit however (as I think it was tricky with leap-days of what is exactly a year period). Instead there is `YS` which saves the restart at the start of the year?

2024-04-30 23:15 UTC, jo-basevi commented on docs/models/run-a-model/run-access-om.md
>  restart_freq: 50Y
Sorry I am not able to link to `restart_freq` in payu's documentation directly but it is under the Model section: https://payu.readthedocs.io/en/latest/config.html#model

2024-05-01 00:42 UTC, atteggiani commented
> Just noticed line 103 (`cd 1deg_jra55_ryf`) is missing a prompt (needs `data=input`).
> 
> I also realised there is no instructions on how to get help. A link to the user support page (https://access-hive.org.au/about/user_support/) would be appropriate.
> 
> These are the form of words I used in the release notice. I think something like this is also worth including as well as the link above:
> 
> > If you have questions about [access-om2](https://forum.access-hive.org.au/tag/access-om2) create a topic in the [COSIMA](https://forum.access-hive.org.au/c/cosima/29) category on the [ACCESS Hive Forum](https://forum.access-hive.org.au) and tag it with [access-om2](https://forum.access-hive.org.au/tag/access-om2). If you require assistance [follow the guidelines for requesting help from ACCESS-NRI ](https://forum.access-hive.org.au/t/access-help-and-support/908).

Fixed vitual terminal prompt, and added 'how to get help' section at the end.
@aidanheerdegen

2024-05-01 01:28 UTC, aidanheerdegen approved these changes
LGTM. Thanks Davide.

2024-05-01 03:57 UTC, merged