Update titles under "Getting Started" section
ACCESS-NRI/access-hive.org.au pull request #717
Opened 2024-08-07 06:21 UTC by paigem

## Description

This PR updates the titles in the `Gettins Started` section. I've made some suggestions here, and would like input from the Hive Docs Team on whether these updated titles make sense.

I tried to update the titles in all locations, including the navigation bar and homepage, but please let me know if I missed anywhere.

Fixes #716 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue, e.g. dead links)
- [ ] New link / content

## Checklist:

- [ ] The new content is accessible and located in the appropriate section
- [ ] My changes do not break navigation and do not generate new warnings
- [ ] I have checked that the links are valid and point to the intended content
- [ ] I have checked my code/text and corrected any misspellings
- [ ] I have chosen the correct tag for the level of [support provided](https://access-hive.org.au/#support)

2024-08-07 07:38 UTC, atteggiani requested changes
I think overall we can improve many sections' titles and how we structure/frame each of the sessions. 
So, thank you @paigem for opening this PR and starting this conversation!

For the specific changes please see the comments under each of those. 

**Note on the PR and the GitHub actions:**
- You started this PR from your fork of this repo, instead of creating a branch directly inside the repo. Is there any specific reason why you chose this approach? In general this is completely fine (and is the recommended approach for an external person that wants to contribute directly) but since you are a member of ACCESS-NRI it might be easier to just create your own branch within the repo itself.
- The [`Deploy to GitHub Pages` action](https://github.com/ACCESS-NRI/access-hive.org.au/actions/runs/10279198051) for this PR failed (deployment and PR comment). I am not completely sure why yet, but I guess it has to do with GITHUB_TOKEN permission within the GitHub workflow (most likely because you started the PR from a fork). This of course has nothing to do with you and it's something we need to fix so it doesn't happen for external people. I rasied an issue and I'll have a look into that.
- You opened the PR to be merged into `ACCESS-NRI:main`, but the correct branch for merging PRs is `ACCESS-NRI:developent`. You might have followed the [Contribute on GitHub](https://access-hive.org.au/about/contribute/contribute_on_github/) guide on the Hive Docs and, in fact, I checked but there is no mention of which branch to select when opening PRs.
I changed the target branch from `ACCESS-NRI:main` to `ACCESS-NRI:development` and I raised an issue to update the instructions on the Hive Docs.

Thank you!!

2024-08-07 07:38 UTC, atteggiani commented on docs/getting_started/index.md
> +# Get Started on NCI
```suggestion
# Getting Started
```
I think this page is intended to be a general "getting started" (which in our case is probably all related to NCI, but doesn't necessarily have to be bound to it). For this reason I don't like your proposed change.
Another issue is also the lengt with your proposed title, that would make the width of this section in the top bar a bit too wide (see also a few comments down).

2024-08-07 07:38 UTC, atteggiani commented on docs/index.md
> +        <div class="bold">New to NCI?</div>
```suggestion
        <div class="bold">Not a NCI user?</div>
```

2024-08-07 07:38 UTC, atteggiani commented on mkdocs.yml
> +    - Set Up and Customize your NCI Account: getting_started/first_steps.md
```suggestion
    - Set Up your NCI Account: getting_started/first_steps.md
```

See a few comments above

2024-08-07 07:38 UTC, atteggiani commented on mkdocs.yml
> +  - Get Started on NCI:
```suggestion
  - Getting Started 
```
See a few comments above on the purpose of this section. 
Also, your suggested title would make the "Get Started on NCI" section title on the top bar (the blue one) much wider than the other sections' titles.

2024-08-08 00:06 UTC, paigem commented on docs/getting_started/first_steps.md
> +# Set Up and Customize your NCI Account
Sounds good, I'm happy to leave it as setting up an NCI account.

2024-08-08 00:08 UTC, paigem commented on docs/getting_started/index.md
> +# Get Started on NCI
I'm happy with this suggestion, paired with the changing of the tagline to being about NCI (as you suggest below in a different suggested edit). Previously I thought it was confusing saying "Get Started" but it was unclear what we were starting, and the tagline suggested it would be a user guide for Hive Docs.

2024-08-08 00:21 UTC, paigem commented on docs/index.md
> +        <div class="bold">New to NCI?</div>
I have a slight preference to leave it as "New to NCI?", mostly because the ARE page could be helpful even for those who have NCI accounts but haven't used it before.

If we stick with your suggestion, then I think it should be "Not _an_ NCI user?" I looked up how NCI refers to themselves in their user guide (e.g. [at this link](https://opus.nci.org.au/pages/viewpage.action?pageId=230490436)) and they use _an_ instead of _a_.

2024-08-08 00:27 UTC, paigem commented
Thanks @atteggiani for your review! I have a few responses below and have also commented directly on your suggested edits.

1. Good question - if I am making minor updates, then I tend to just create a new branch directly, but if I'm making more significant changes I usually end up pushing from my own fork so I can preview changes locally. Plus, I find it a bit more straightforward to do it this way when I'm making updates to several different files (but that's likely just because it's what I'm used to!). I probably didn't need to do that this time around, but since I was changing wording in the table of contents, I thought it was best if I preview my changes before pushing. Let me know if you'd prefer I just create a branch within the main repo next time.
2. Hmm, there's certainly a chance that I messed something up in my local copy. Let me know if there's something I should fix, or if I should redo the PR from a branch instead.
3. I actually had this question when submitting the PR, but opted to continue instead of reaching out to ask. I did indeed look at the instructions in the contributor guide, and saw that it didn't mention which branch. If you've updated the target branch, then that's great, and thanks for raising an issue to update the guide. 😊

2024-08-08 00:39 UTC, atteggiani commented on docs/index.md
> +        <div class="bold">New to NCI?</div>
That is true. 
In general I don't like "New to NCI?" for two main reason: 
- If a new user comes to the Hive Docs, they will most likely know the term "Hive Docs" (because they're in that website), but they might never have heard the term "NCI". So it would seem weird to me having to click a link that is referenced with a term I'm not familiar with.
- Writing "New to NCI" we move the focus on NCI rathe than on the Hive Docs. I understand that, to get started, a new user will have to get familiar with NCI (create an NCI account, etc.). However, the "Getting Started" section was intended to be a section that new users will have to go through if they want to be able to understand and apply the content of most of other pages within the Hive Docs (for example the "How to run ..." pages).

I agree that my suggestion would create issues and still not solve these problems, so I think we might need a different solution but I am not sure what that could be.

2024-08-08 01:46 UTC, atteggiani commented
> Thanks @atteggiani for your review! I have a few responses below and have also commented directly on your suggested edits.
> 
> 1. Good question - if I am making minor updates, then I tend to just create a new branch directly, but if I'm making more significant changes I usually end up pushing from my own fork so I can preview changes locally. Plus, I find it a bit more straightforward to do it this way when I'm making updates to several different files (but that's likely just because it's what I'm used to!). I probably didn't need to do that this time around, but since I was changing wording in the table of contents, I thought it was best if I preview my changes before pushing. Let me know if you'd prefer I just create a branch within the main repo next time.

That is completely fine and if you are used to that workflow I think there shouldn't be any problems.
However, if you consider to add your changes to a branch of a cloned repo instead (in the future), just two notes:
- For the "preview changes locally" part, you can do that in the same way you would for a forked repo. The recommended way to preview your work is to use `mkdocs serve` as illustrated in [Deploying Website Preview](https://access-hive.org.au/about/contribute/contribute_on_github/#deploying-website-preview).
- For a cloned repo, it would be a bit easier and linear to keep it updated with the remote repo. However, you can do that even with a forked repo, more details at point 3.

> 2. Hmm, there's certainly a chance that I messed something up in my local copy. Let me know if there's something I should fix, or if I should redo the PR from a branch instead.

No I am pretty confident this is not your fault. It might be related to your PR coming from an external fork instead of an internal branch, but I still do not know why that happens. In any case, this should NOT happen, and will have to be fixed within the deployment workflow. This PR is perfectly fine.

> 3. I actually had this question when submitting the PR, but opted to continue instead of reaching out to ask. I did indeed look at the instructions in the contributor guide, and saw that it didn't mention which branch. If you've updated the target branch, then that's great, and thanks for raising an issue to update the guide. 😊

Yeah, no problem! 
The only other thing you might need, is to get your feature branch (in your case the `paigem:main`) up to date with `ACCESS-NRI:development`. 
This is in general a step you should always do to make sure that your feature branch is updated with the **default** branch for the Hive Docs repo which is `development`. 
This step would be easier and more commonly done for a cloned repo, but can be achieved also for a forked repo.
More instructions are listed in [Syncing a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) but, in general, you would have to do something along the lines of:
```sh
git fetch upstream -Pp
git checkout <your-feature-branch>
git rebase upstream/development # you can also use 'git merge' but I prefer 'git reabase' 
# You might need to resolve conflicts generated by the rebase/merge
git push
```

2024-08-20 01:13 UTC, paigem commented
Based on our discussion during our meeting, we can use the phrase "New ACCESS user?"

We should also add a sentence or two on the "Getting Started" page to add a bit of text around what is needed for new ACCESS users.

2024-08-20 05:57 UTC, flicj191 commented on docs/index.md
> +        <div class="bold">New to NCI?</div>
```suggestion
        <div class="bold">New ACCESS user?</div>
```

2024-08-20 06:13 UTC, flicj191 requested changes
Thanks @paigem, I'll approve and merge once those couple things are done

2024-08-20 06:13 UTC, flicj191 commented on docs/getting_started/index.md
Short description for this page, @paigem See a suggestion below but happy for you to add in what you see fit then I can finish the review 😊

*If you have never used NCI Gadi for ACCESS models, run through these two pages to get set up. If you already have an NCI account but have never used ARE, it is a web-based interface to Gadi that is useful for many ACCESS-related activities.*

2024-08-21 02:41 UTC, paigem commented on docs/getting_started/index.md
Great suggestion @flicj191 - I added your wording!

2024-08-21 02:43 UTC, flicj191 approved these changes

2024-08-21 02:49 UTC, merged