683 update access esm how to run
ACCESS-NRI/access-hive.org.au pull request #726
Opened 2024-08-14 06:48 UTC by blimlim

## Description

This pull request updates the [run access esm tutorial](https://access-hive.org.au/models/run-a-model/run-access-esm/) to match the structure of the OM2 tutorial, and to include changes related to the latest payu updates and the (to be) released configurations.

Fixes #683 

## Type of change
- [x] New link / content

## Checklist:

- [x] The new content is accessible and located in the appropriate section
- [x] My changes do not break navigation and do not generate new warnings
- [x] I have checked that the links are valid and point to the intended content
- [ ] I have checked my code/text and corrected any misspellings
- [ ] I have chosen the correct tag for the level of [support provided](https://access-hive.org.au/#support)

2024-08-22 00:04 UTC, blimlim commented
Hi everyone, I've finally finished adding in some of the more ESM1.5 specific information now that the changes to the configurations and payu are (mostly) finalised and I think it's ready for a review. 

The following two points are still waiting on further information/links, but everything else should be ready for a review:

- The required payu version might need to wait until the final updates to payu are released.
- Links to the released configurations on github will have to wait until the release- branches are ready.

Sorry about the delay on this!

2024-08-22 00:29 UTC, KAUR1984 commented
Thanks for that @blimlim! Looks great to me!

I would perhaps suggest to merge this PR into the development branch for now. For the rest of the changes, happy to create a new PR and once we have all the changes, we can deploy it on the main branch. :)

2024-08-22 00:29 UTC, KAUR1984 approved these changes

2024-08-22 00:38 UTC, blimlim commented
Thanks @KAUR1984! I just realised there were a couple of spelling errors which I've just fixed up, and then will merge into development

2024-08-22 01:21 UTC, aidanheerdegen commented
I'm part way through reviewing. Should I just close off that review and allow you to make the suggested changes?

2024-08-22 01:26 UTC, blimlim commented
That sounds good! I'll wait until I've added any suggested changes before merging.

2024-08-22 02:46 UTC, aidanheerdegen requested changes
Thanks @blimlim! Awesome work.

I have made a number of suggestions, not all are necessarily required, happy to leave it to you to decide what to keep and what to not, or further modify.

I have some thoughts about the post-processing, but that may require changes to the script invocation, which will then have to be changed here to be consistent.

2024-08-22 02:46 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-esm.md
> +    To have a _total experiment length_ of 7 years with a 3-year resubmission cycle, leave [`runtime`](#runtime) as the default value of `1 year` and set `runspersub` to `3`. Then, run the configurat
```suggestion
    To have a _total experiment length_ of 7 years with a 3-year resubmission cycle, leave [`runtime`](#runtime) as the default value of `1 year`, set `runspersub` to `3` and `walltime` to `6:00:00`. Then, run the configuration with `-n` set to `7`:
```

2024-08-22 02:46 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-esm.md
> +
```suggestion
!!! tip
    The `walltime` must be set to be long enough that the PBS job can complete. The model usually runs a single year in 90 minutes or less, but the `walltime` for a single model run is set to `2:30:00` out of an abundance of caution to make sure the model has time to run when there are occasional slower runs for unpredicatable reasons. When setting `runspersub > 1` the `walltime` doesn't need to be a simple multiple of `2:30:00` because it is highly unlikely that there will be multiple anomalously slow runs per submit.
```

2024-08-22 02:46 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-esm.md
> +With the default configuration settings, the sea ice component of {{ model }} will produce restart files only at the end of each year. If valid restart files are required when running shorter simulat
```suggestion
With the default configuration settings, the sea ice component of {{ model }} will produce restart files only at the end of each year. If valid restart files are required when running shorter simulations, the sea ice model configuration should be modified so that restart files are produced at monthly frequencies. To do this, change the `dumpfreq = 'y'` setting to `dumpfreq = 'm'` in the `cice_in.nml` configuration file located in the `ice` subdirectory of the control directory.
```

2024-08-22 02:46 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-esm.md
> +For example, to run {{ model }} under the `ol01` project (COSIMA Working Group), uncomment the line beginning with `# project` by deleting the `#` symbol and replace `PROJECT_CODE` with `ol01`:
```suggestion
By default the model will be submitted to the PBS queue using your default project.  To run {{ model }} using the resources of a specific project, for example the `lg87` project (ESM Working Group), uncomment the line beginning with `# project` by deleting the `#` symbol and replace `PROJECT_CODE` with `lg87`:
```

2024-08-22 02:46 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-esm.md
> +project: ol01
```suggestion
project: lg87
```

2024-08-22 02:46 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-esm.md
> +    Doing this will make sure the same `/scratch` location is used for the _laboratory_, regardless of which project is used to run the experiment.
```suggestion
    If more than one project is used to run an {{ model }} configuration the `shortpath` option also needs to be uncommented and the path to the desired `/scratch/PROJECT_CODE` directory added.<br>
    This ensures the same `/scratch` location is used for the _laboratory_, regardless of which project is used to run the experiment.
```

2024-08-22 02:46 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-esm.md
> +    The {{model}} default configurations include a postprocessing [postcript](#postscripts) which converts atmospheric outputs to NetCDF format and runs in a separate PBS job. This prevents the final
```suggestion
    The {{model}} configurations include a postprocessing [postcript](#postscripts) which converts atmospheric outputs to NetCDF format. This runs in a separate PBS job and this prevents the output and restart files of the most recent run from being automatically synced. When a series of runs completes and the final post-processing is completed run `payu sync` in the control directory to sync the final outputs and restarts.
```

2024-08-22 02:46 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-esm.md
> +Rather than outputting a single diagnostic file over the whole model horizontal grid, the ocean component [MOM](/models/model_components/ocean/#modular-ocean-model-mom) typically generates diagnostic
```suggestion
Rather than outputting a single diagnostic file over the whole model horizontal grid, the ocean component [MOM](/models/model_components/ocean/#modular-ocean-model-mom) typically generates diagnostic outputs as tiles, each of which spans a portion of model grid.
```

2024-08-22 02:46 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-esm.md
> +A dictionary to run scripts or subcommands at various stages of a _payu_ submission. The above example comes from the `release-historical+concentrations` configuration, where the ```update_landuse_dr
```suggestion
Run scripts or subcommands at various stages of a _payu_ submission. The above example comes from the `release-historical+concentrations` configuration, where the ```update_landuse_driver.sh``` is used to apply historical land use changes at the end of each run.
```

2024-08-22 03:33 UTC, blimlim commented
Thanks for spotting those things – I think they're all good suggestions and I've added them in. 

> I have some thoughts about the post-processing, but that may require changes to the script invocation, which will then have to be changed here to be consistent.

Sounds good, lets see if we can simplify how the script is called.

2024-08-22 03:34 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-esm.md
> +To enable syncing, change `enable` to `True`, and set `path` to a location on `/g/data`, where _payu_ will copy output and restart folders. A sensible `path` could be: `/g/data/$PROJECT/$USER/{{model
```suggestion
To enable syncing, change `enable` to `True`, and set `path` to a location on `/g/data`, where _payu_ will copy output and restart folders.
```

We don't want users literally putting environment variables in the sync path, so I've suggested we just remove that bit as it got a little confusing trying to suggest something with a bunch of placeholders that needed to be explained and replaced for limited utility.

2024-08-22 04:46 UTC, blimlim commented on docs/models/run-a-model/run-access-esm.md
> +To enable syncing, change `enable` to `True`, and set `path` to a location on `/g/data`, where _payu_ will copy output and restart folders. A sensible `path` could be: `/g/data/$PROJECT/$USER/{{model
Good idea, I've just added this in. This section was copied from the OM2 docs – should I add an issue to add the same update there?

2024-08-23 07:14 UTC, blimlim commented
I've just updated the docs with the change to the NetCDF conversion behaviour and added in the correct payu version. After looking over everything, I think the information is now correct.

2024-08-23 07:41 UTC, aidanheerdegen approved these changes
Looks great, thanks for all the hard work.

2024-08-26 02:01 UTC, atteggiani commented on docs/models/run-a-model/run-access-esm.md
> +{% set model = "ACCESS-ESM1.5" %}
Solved in my recent [commit](https://github.com/ACCESS-NRI/access-hive.org.au/pull/726/commits/76bdfbfa2e885d412914e9b84e218b960ad752af)

2024-08-26 02:01 UTC, atteggiani commented on docs/models/run-a-model/run-access-esm.md
>  ```
Solved in my recent [commit](https://github.com/ACCESS-NRI/access-hive.org.au/pull/726/commits/76bdfbfa2e885d412914e9b84e218b960ad752af)

2024-08-26 02:01 UTC, atteggiani commented on docs/models/run-a-model/run-access-esm.md
> +```
Solved in my recent [commit](https://github.com/ACCESS-NRI/access-hive.org.au/pull/726/commits/76bdfbfa2e885d412914e9b84e218b960ad752af)

2024-08-26 02:01 UTC, atteggiani commented on docs/models/run-a-model/run-access-esm.md
> +Postprocessing scripts that need to be run after _payu_ has completed all steps that might alter the output directory can be run as postscripts. These run in separate PBS jobs than the main model sim
Solved in my recent [commit](https://github.com/ACCESS-NRI/access-hive.org.au/pull/726/commits/76bdfbfa2e885d412914e9b84e218b960ad752af)

2024-08-26 02:01 UTC, atteggiani commented on docs/models/run-a-model/run-access-esm.md
> +All {{ model }} configurations include the above NetCDF conversion postscript, which converts the atmosphere model's fields file format output to NetCDF in order to aid analysis and reduce storage re
Solved in my recent [commit](https://github.com/ACCESS-NRI/access-hive.org.au/pull/726/commits/76bdfbfa2e885d412914e9b84e218b960ad752af)

2024-08-26 02:40 UTC, aidanheerdegen requested changes
Just one small change, otherwise looks good and thanks for the changes.

2024-08-26 02:40 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-esm.md
> +    <terminal-line>To change directory to _control_ directory run:</terminal-line>
This formatting seems to break in the terminal emulator. The word has disappeared in the preview.

I assume this change was unintentional.

2024-08-26 03:42 UTC, atteggiani commented on docs/models/run-a-model/run-access-esm.md
> +    <terminal-line>To change directory to _control_ directory run:</terminal-line>
Oops I just did a "replace all" and missed that that was inside a terminal window 😅 
Fixed!

2024-08-26 03:42 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-esm.md
> +    <terminal-line>To change directory to _control_ directory run:</terminal-line>
I figured.

2024-08-26 03:44 UTC, aidanheerdegen approved these changes
Looks great. Thanks!

2024-08-26 03:50 UTC, merged