Jasmeen/change tagline 728
ACCESS-NRI/access-hive.org.au pull request #740
Opened 2024-08-27 02:44 UTC by KAUR1984

Fixes the issue #728

2024-08-27 02:49 UTC, flicj191 commented on docs/index.md
>          <div>Welcome to ACCESS-Hive!</div>
```suggestion
        <div>Welcome to ACCESS-Hive Docs!</div>
```

2024-08-27 02:51 UTC, flicj191 requested changes
See comment for updating name

2024-08-28 02:22 UTC, KAUR1984 commented
@flicj191 comment addressed in the PR - #746.

2024-08-28 02:23 UTC, flicj191 approved these changes

2024-08-28 02:23 UTC, flicj191 approved these changes

2024-08-28 05:56 UTC, merged