getting_started/spack.md: provide instructions on updating
ACCESS-NRI/access-hive.org.au pull request #817
Opened 2024-10-01 05:14 UTC by harshula

2024-10-01 05:58 UTC, atteggiani requested changes
Thank you @harshula for the PR.

Looks pretty good, just a few minor comments.

2024-10-01 05:58 UTC, atteggiani commented on docs/getting_started/spack.md
> +
```suggestion
```

I think the idea of "versioning" the docs make sense, but it's a bigger issue that should involve the whole Hive Docs. 
For a "last update" message, there is already a line (enabled with the [mkdocs-git-revision-date-localized-plugin](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin)) at the bottom of each page on the Hive Docs.

2024-10-01 05:58 UTC, atteggiani commented on docs/getting_started/spack.md
> +!!! warning
```suggestion
!!! tip
```

I would change that to a "tip", but just my preference.

2024-10-01 05:58 UTC, atteggiani commented on docs/getting_started/spack.md
> +    ACCESS-NRI maintains a fork of spack to enable back-porting fixes from more recent spack versions. This fork is the one used in these instructions.
```suggestion
    ACCESS-NRI maintains a [fork of spack](https://github.com/ACCESS-NRI/spack) to enable back-porting fixes from more recent spack versions. This fork is the one used in these instructions.
```

2024-10-01 12:58 UTC, harshula commented on docs/getting_started/spack.md
> +
Thanks! I'll remove this.

2024-10-01 12:59 UTC, harshula commented on docs/getting_started/spack.md
> +!!! warning
Will do.

2024-10-01 13:02 UTC, harshula commented on docs/getting_started/spack.md
> +    ACCESS-NRI maintains a fork of spack to enable back-porting fixes from more recent spack versions. This fork is the one used in these instructions.
Will do

2024-10-02 00:17 UTC, atteggiani approved these changes
Looks good. 

Thanks @harshula!

2024-10-02 01:01 UTC, merged