getting_started/spack.md: incorporate feedback
ACCESS-NRI/access-hive.org.au pull request #824
Opened 2024-10-10 12:03 UTC by harshula

2024-10-14 21:48 UTC, atteggiani requested changes
Thank you for this PR @harshula.
Overall I like the updates. 
There are a couple of things I would change and a few missing coloured outputs (see comments).
I am happy to work on the suggestions/coloured outputs if it's ok for you.

2024-10-14 21:48 UTC, atteggiani commented on docs/getting_started/spack.md
> +
This part should go under Test Spack.

2024-10-14 21:48 UTC, atteggiani commented on docs/getting_started/spack.md
> +```
Replace with the Enable Spack above.

2024-10-14 21:48 UTC, atteggiani commented on docs/getting_started/spack.md
> +</terminal-window>
Colour classes not present in this file. 
In [build_a_model](https://access-hive.org.au/pr-preview/pr-824/models/run-a-model/build_a_model/) they are present in the page markdown file.
Since we're using them in more than one page, it might be convenient to rename them to something more sensible (for example by prepending `spack-`, e.g. `spack-indigo`, `spack-cyan`, etc.) and add them to the general CSS.

2024-10-14 21:48 UTC, atteggiani commented on docs/getting_started/spack.md
> +### Start compiling
```suggestion
### Compile packages
```

2024-10-14 21:48 UTC, atteggiani commented on docs/getting_started/spack.md
>  spack env activate -p test
I would add this line above at the end of "Create the Spack managed environment".

2024-10-14 21:48 UTC, atteggiani commented on docs/getting_started/spack.md
> +</terminal-window>
Missing coloured output.

2024-10-14 21:48 UTC, atteggiani commented on docs/getting_started/spack.md
> +</terminal-window>
1. Missing coloured output
2. I would omit the lines that list the steps for each package being installed e.g.:
  ```
  ==> No binary for access-test-git.2024.09.20=2024.09.20-hmy75yl26hexivgsw7zhlvbnjgst3gwc found: installing from source
  ==> No patches needed for access-test
  ==> access-test: Executing phase: 'install'
  ==> access-test: Successfully installed access-test-git.2024.09.20=2024.09.20-hmy75yl26hexivgsw7zhlvbnjgst3gwc
  Stage: 0.00s.  Install: 0.00s.  Post-install: 0.37s.  Total: 1.77s
  ```
  as in the [build_a_model](https://access-hive.org.au/development-website/models/run-a-model/build_a_model/) install outputs.

2024-10-14 21:48 UTC, atteggiani commented on docs/getting_started/spack.md
> +</terminal-window>
Missing coloured output.

2024-10-15 01:41 UTC, harshula commented on docs/getting_started/spack.md
> +
IIRC, @chrisb13 wanted this moved from the `Test Spack` to the `Set up Spack on Gadi`.

2024-10-15 01:43 UTC, harshula commented on docs/getting_started/spack.md
> +</terminal-window>
Spack specific styles would be great!

2024-10-15 02:24 UTC, atteggiani commented on docs/getting_started/spack.md
> +
Setup steps are steps that need to be done once only (as specified also in the [admonition](https://access-hive.org.au/pr-preview/pr-824/getting_started/spack/#set-up-spack-on-gadi)).
That step is required every time the user logs in to `Gadi` (or for any new shell, as specified by its admonition). Therefore, I wouldn't consider that as a setup step.

2024-10-15 03:02 UTC, harshula commented on docs/getting_started/spack.md
> +</terminal-window>
How do you get the formatting of the columns to be replicated?

2024-10-15 05:39 UTC, harshula commented on docs/getting_started/spack.md
> +
Hi, As discussed `Enable Spack` is now one level higher and outside of `Set up Spack on Gadi`.

2024-10-15 05:39 UTC, harshula commented on docs/getting_started/spack.md
> +```
As discussed, deleted.

2024-10-15 05:39 UTC, harshula commented on docs/getting_started/spack.md
> +### Start compiling
Done

2024-10-15 05:43 UTC, harshula commented on docs/getting_started/spack.md
>  spack env activate -p test
Keeping the same for the moment.

2024-10-15 13:00 UTC, harshula commented on docs/getting_started/spack.md
> +</terminal-window>
Completed Point 2.

2024-10-15 23:33 UTC, blimlim reviewed
These instructions look good and are easy to follow!

I've just added a few questions/comments that came up when I went through the instructions. I don't think they're crucial, so feel free to make changes if they seem relevant and skip them if not!

2024-10-15 23:33 UTC, blimlim commented on docs/getting_started/spack.md
I'm wondering if it would it be helpful to link to the "build an access model" instructions at this point. When I got to this step, my thought was "Oh cool! Oh what's the next step, how do I go from here to working on the model?" and it I wasn't sure where to go for the next set of instructions.

2024-10-15 23:33 UTC, blimlim commented on docs/getting_started/spack.md
>  Keep your Spack instance up-to-date by doing the following:
A couple of questions came up when I got to this part – there's probably no need to answer them though as I'm not sure how common they'd be:
- Would updating Spack ever impact any of your existing environments?
- Are there any risks if you don't keep your spack up to date, or benefits if you do? (I'm sometimes lazy and often drag my feet on updating software, and so pointing out why I should regularly update it could be  a good motivator. Not sure if other people are the same though).

2024-10-15 23:33 UTC, blimlim commented on docs/getting_started/spack.md
> +
I think it could be helpful to briefly explain the reason someone might want to run the tests, e.g. is it to check that your installation has worked properly?

2024-10-15 23:43 UTC, harshula commented on docs/getting_started/spack.md
Good idea. @atteggiani ?

2024-10-16 02:52 UTC, atteggiani commented on docs/getting_started/spack.md
That's a great point @blimlim! 
I'm gonna add a mention at the end of the Spack setup (before the test).

2024-10-16 03:05 UTC, atteggiani commented on docs/getting_started/spack.md
>  Keep your Spack instance up-to-date by doing the following:
These questions make sense:

I'll give my answers, but if anything is imprecise please correct me @harshula.

> Would updating Spack ever impact any of your existing environments?

It might, but we need to be precise about what we mean when we refer to "impacting existing environments": the existing environment configuration files (spack.yaml) would never change. The directory where (new) environments are located might change, but this would not affect the behaviour of an environment itself. What might change (depending on the new spack version configurations) 

> Are there any risks if you don't keep your spack up to date, or benefits if you do? (I'm sometimes lazy and often drag my feet on updating software, and so pointing out why I should regularly update it could be a good motivator. Not sure if other people are the same though).

2024-10-16 04:15 UTC, atteggiani commented on docs/getting_started/spack.md
>  Keep your Spack instance up-to-date by doing the following:
These questions make sense:

I'll give my answers, but if anything is imprecise please correct me @harshula.

> Would updating Spack ever impact any of your existing environments?

The general answer is: it might.
A lot depends on the core changes (_Spack_ functionality changes) that come with the new version. That we cannot control and we don't know in advance.
However, for what we can control, thinking as if there were no functional changes that impact environments functionality in new versions of _Spack_ (as it is likely to be), the following points are valid: 
- any existing environment configuration file (`spack.yaml`) would never change. The directory where (new) environments are located might change, but this would not affect the behaviour of an environment itself. In any case, we can minimise this issue by setting the default environments location for the _Spack_ instances outside of the instance folder (as it is currently done through the [config.yaml](https://github.com/ACCESS-NRI/spack-config/blob/d4480acfb7ed0f0ac2dc6cf73bd959a2cff56511/common/config.yaml#L8)'s `environments_root` field, where the environments folder is set at the same level as the instance folder). This ensures that, with new _Spack_ versions, the environments folder will still be the same.

- for impacts related to which packages/packages versions are installed by the (old) environments, it massively depends on _Spack_'s multiple configuration files. If the updated _Spack_ instance comes with the same configurations as the "old" _Spack_ version, then everything is likely to work as it did before. This is something we can (almost completely) control.

Therefore, I would say for the most part we can control and ensure that a new _Spack_ versions would still build an "old" environment as an "old" _Spack_ version would (and we should ensure it!).

> Are there any risks if you don't keep your spack up to date, or benefits if you do?

Again, this depends on any new "core" functionality that we might need to use in the future. I would say, in general, it is advised to keep software up to date (unless there are specific contraindications to that), but if there are no "big" updates in the _Spack_ functionality I would not expect to have major practical impacts.
However, for complete reproducibility we should be able to choose which _Spack_ version we want to use.

In any case, both of these points should be addressed and be (almost completely) solved by reworking the _Spack_ workflow into using a _Spack_ `module` that can be loaded with the latest (or any selected) _Spack_ version and default configurations. This will hopefully happen soon! :D

2024-10-16 04:16 UTC, atteggiani commented on docs/getting_started/spack.md
> +
I will change "To test _Spack_ ..." to "To test that your _Spack_ installation works as expected, ..."

2024-10-17 01:48 UTC, atteggiani approved these changes

2024-10-17 01:50 UTC, atteggiani commented
Addressed all comments. 
@harshula you cannot formally review (because you opened the PR), but please check if this looks good to you now.

2024-10-17 02:43 UTC, blimlim approved these changes
Changes look good to me! 

I've just added a small suggestion but don't think it's 100% necessary.

2024-10-17 02:43 UTC, blimlim commented on docs/getting_started/spack.md
> +    This page is tailored to experienced users and collaborators developing ACCESS models. This step is *not* required if you *only* want to run a model.
My suggestion isn't crucial, but I'm thinking it could be helpful to link to the Run a Model page here for people who've found themselves on the wrong page.

2024-10-17 02:47 UTC, atteggiani commented on docs/getting_started/spack.md
> +    This page is tailored to experienced users and collaborators developing ACCESS models. This step is *not* required if you *only* want to run a model.
Yeah it makes sense!

2024-10-17 02:52 UTC, atteggiani commented on docs/getting_started/spack.md
> +    This page is tailored to experienced users and collaborators developing ACCESS models. This step is *not* required if you *only* want to run a model.
Addressed in [130de67ba4a597cf153a8718197d542d4190c480](https://github.com/ACCESS-NRI/access-hive.org.au/pull/824/commits/130de67ba4a597cf153a8718197d542d4190c480)

2024-10-17 04:38 UTC, atteggiani commented
> Hi @atteggiani , Looks good. One problem is the `spack install` output. It's the wrong output.

Fixed the compiler version.

2024-10-17 05:59 UTC, merged

2024-10-17 06:00 UTC, atteggiani commented
Thank you @harshula and @blimlim.
Merged.

2024-10-19 12:18 UTC, harshula commented on docs/getting_started/spack.md
>  Keep your Spack instance up-to-date by doing the following:
Hi @blimlim ,

> Would updating Spack ever impact any of your existing environments?

If you are referring to the binaries that have already been built, it should not.

> Are there any risks if you don't keep your spack up to date, or benefits if you do? 

Are you referring to the `spack` git repo only? There are also the `spack-config` and `spack-packages`. Have a look at `spack-packages` & `spack-config` repo commits to better understand why they should be kept up-to-date. The `spack` repo update only pulls bugfixes via upstream minor version releases.