Paula/fix broken links
ACCESS-NRI/access-hive.org.au pull request #836
Opened 2024-10-28 00:12 UTC by pboubel

## Description

Fixes #826 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue, e.g. dead links)

## Checklist:

- [ ] The new content is accessible and located in the appropriate section
- [ ] My changes do not break navigation and do not generate new warnings
- [ ] I have checked that the links are valid and point to the intended content
- [ ] I have checked my code/text and corrected any misspellings
- [ ] I have chosen the correct tag for the level of [support provided](https://access-hive.org.au/#support)

When your pull request is ready please [request a review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review). 

Unless there is a specific person you want your PR to be reviewd by, please select the **WebOps team**: `ACCESS-NRI/WebOps`. This ensures the load for reviewing pull requests is shared equitably.

2024-12-03 22:07 UTC, atteggiani requested changes
Thank you @pboubel for working on this! 

You've done a great job correcting the various links and fixing a few other styling issues. 

I have added some very minor suggestions. 

On a more general side, I would bump the [lychee-action](https://github.com/lycheeverse/lychee-action) used in the [check-links.yml](https://github.com/ACCESS-NRI/access-hive.org.au/blob/paula/fix-broken-links/.github/workflows/check_links.yml) to the [latest version](https://github.com/lycheeverse/lychee-action/releases/tag/v2.1.0) (`2.1.0`, commit ref: `f81112d0d2814ded911bd23e3beaa9dda9093915`). Currently we are using version `1.10` and the issue with the failing link seems to be solved with the new version (or at least it didn't pick it when I ran it locally).
However, the new version failed two other links (not sure why), but if that's still the case we will address it.
The changes would be at line 26 of the `check-links.yml`:
https://github.com/ACCESS-NRI/access-hive.org.au/blob/6a7b4d2b54b26ba455d4c124b68a78682cb64d8f/.github/workflows/check_links.yml#L26

```diff
-       uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 #v1.10.0
+       uses: lycheeverse/lychee-action@f81112d0d2814ded911bd23e3beaa9dda9093915 #v2.1.0
```


Thank you!

2024-12-06 02:49 UTC, pboubel commented on docs/models/run-a-model/run-access-om.md
> +All {{model}} configurations are open source, licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1")![CC icon](https://mirrors.creativecommons.org/presskit/icons/cc.
Hi @atteggiani, the double curly braces here and in run-access-esm.md are generating errors with the link checker. Any clue how to fix this?

2024-12-06 02:57 UTC, pboubel commented on docs/models/run-a-model/build_a_model.md
> +As an example, in the following instructions we will show how to modify [mom5 component](/models/model_components/ocean/#mom5) for [ACCESS-ESM1.5](/models/configurations/access-esm/#access-esm15) and
Yes, they cause '404' errors which is why I removed them

2024-12-06 03:03 UTC, pboubel commented
> Thank you @pboubel for working on this!
> 
> You've done a great job correcting the various links and fixing a few other styling issues.
> 
> I have added some very minor suggestions.
> 
> On a more general side, I would bump the [lychee-action](https://github.com/lycheeverse/lychee-action) used in the [check-links.yml](https://github.com/ACCESS-NRI/access-hive.org.au/blob/paula/fix-broken-links/.github/workflows/check_links.yml) to the [latest version](https://github.com/lycheeverse/lychee-action/releases/tag/v2.1.0) (`2.1.0`, commit ref: `f81112d0d2814ded911bd23e3beaa9dda9093915`). Currently we are using version `1.10` and the issue with the failing link seems to be solved with the new version (or at least it didn't pick it when I ran it locally). However, the new version failed two other links (not sure why), but if that's still the case we will address it. The changes would be at line 26 of the `check-links.yml`:
> 
> https://github.com/ACCESS-NRI/access-hive.org.au/blob/6a7b4d2b54b26ba455d4c124b68a78682cb64d8f/.github/workflows/check_links.yml#L26
> 
> ```diff
> -       uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 #v1.10.0
> +       uses: lycheeverse/lychee-action@f81112d0d2814ded911bd23e3beaa9dda9093915 #v2.1.0
> ```
> 
> Thank you!

Hi @atteggiani thanks for the review! The new version of lychee shows does indeed pass on that link that was failing earlier, and I don't see any new errors (just the ones that pop up any time we use a Jinja2 replacement variable).

2024-12-06 04:29 UTC, atteggiani commented on docs/models/run-a-model/run-access-om.md
> +All {{model}} configurations are open source, licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1")![CC icon](https://mirrors.creativecommons.org/presskit/icons/cc.
I think the only solution is to exclude those links from being checked. I think it still fine because the "main" link (the one that defined in the replacement variable) would still be checked, so we are still checking each replaced link at least once.

To exlude the links I would add the following string in the `lychee-config.toml` `exclude` list:
```
`{{[^}]*}}`
```
Which matches any link having double brackets in it. 
In case it still fails, we might have to turn the brackets to `%7B` and `%7D`, as they are represented in the failed links of the [link check error](https://github.com/ACCESS-NRI/access-hive.org.au/actions/runs/12192112462/job/34012164791?pr=836).

2024-12-12 23:54 UTC, flicj191 approved these changes

2024-12-12 23:56 UTC, flicj191 commented
Great work @pboubel ! I think we should merge this work into development and create another issue for the more specific link issues so this doesn't sit here and fall out of date. Cheers!

2024-12-13 00:00 UTC, merged