Add Page on How-To Prerelease
ACCESS-NRI/access-hive.org.au pull request #851
Opened 2024-12-05 02:08 UTC by CodeGat

# ACCESS-Hive Docs

## Description

Adds a page under `Run A Model` regarding how to create Prerelease Model Deployments via the Pull Request process in Model Deployment Repositories. This work is based on https://github.com/ACCESS-NRI/model-deployment-template/blob/80117aaad00cdff0cab70e567790e73a183a9267/CONTRIBUTING.md.

Fixes #843
Fixes ACCESS-NRI/build-cd#163

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue, e.g. dead links)
- [x] New link / content

## Checklist:

- [x] The new content is accessible and located in the appropriate section
- [ ] My changes do not break navigation and do not generate new warnings
- [ ] I have checked that the links are valid and point to the intended content
- [x] I have checked my code/text and corrected any misspellings
- [ ] I have chosen the correct tag for the level of [support provided](https://access-hive.org.au/#support)

2025-01-14 04:57 UTC, CodeGat commented
Interesting - using GitHubs own `Update and Rebase` option leads to unverified commits!

2025-01-14 05:44 UTC, atteggiani commented
> Interesting - using GitHubs own `Update and Rebase` option leads to unverified commits!

Yeah, apparently there is no way around that (other than not using it from the Web Interface) 
It's a bummer.

2025-01-15 03:21 UTC, CodeGat commented
@atteggiani I've just rebased so my commits are verified so merging works eventually :laughing:

2025-01-19 23:26 UTC, atteggiani requested changes

2025-01-19 23:26 UTC, atteggiani commented on docs/models/run-a-model/create-a-prerelease.md
> +<span style="color: red">NOTE: Are there any relevant prerequisites??</span>
To keep only if there are relevant prerequisites to be listed.

2025-01-19 23:48 UTC, CodeGat commented on docs/models/run-a-model/create-a-prerelease.md
> +<span style="color: red">NOTE: Are there any relevant prerequisites??</span>
Done in https://github.com/ACCESS-NRI/access-hive.org.au/pull/851/commits/1f30be64bd922fe6897c39c12c3b59e8d150551b

2025-01-19 23:49 UTC, CodeGat commented on docs/assets/model/Pr_Process.svg
That's fair enough. I took it from Aidan :D Would be it okay to leave it out for now?

2025-01-20 00:36 UTC, atteggiani commented on docs/assets/model/Pr_Process.svg
Sure! 
I'll remove that bit.

2025-01-20 00:48 UTC, atteggiani commented on docs/models/run-a-model/create-a-prerelease.md
> +<span style="color: red">NOTE: Are there any relevant prerequisites??</span>
I am updating them (to make them more conform to the other prerequisites).
For the "`write` permissions to the related Model Deployment Repository", would it be good to add a line about what to do in case they don't have `write` permission? 
Something like:
"To request `write` permissions, please contact ..."?

2025-01-20 00:50 UTC, CodeGat commented on docs/models/run-a-model/create-a-prerelease.md
> +<span style="color: red">NOTE: Are there any relevant prerequisites??</span>
That is a good idea. Although, I actually don't know who the central contact would be for requesting write permissions to our repositories!

2025-01-20 00:55 UTC, atteggiani commented on docs/models/run-a-model/create-a-prerelease.md
> +<span style="color: red">NOTE: Are there any relevant prerequisites??</span>
Hmm should I just add a general "contact ACCESS-NRI" for now?

2025-01-20 01:01 UTC, CodeGat commented on docs/models/run-a-model/create-a-prerelease.md
> +<span style="color: red">NOTE: Are there any relevant prerequisites??</span>
I think so!

2025-01-20 01:02 UTC, atteggiani commented on docs/models/run-a-model/create-a-prerelease.md
> +<span style="color: red">NOTE: Are there any relevant prerequisites??</span>
Done in [8907004f24b14080671eff6501dfa59ff6bc1e02](https://github.com/ACCESS-NRI/access-hive.org.au/pull/851/commits/8907004f24b14080671eff6501dfa59ff6bc1e02)

2025-01-20 01:06 UTC, CodeGat reviewed
I think it looks good for an approval!

2025-01-20 01:08 UTC, atteggiani approved these changes

2025-01-20 01:13 UTC, CodeGat commented
There seems to be an error: https://github.com/ACCESS-NRI/access-hive.org.au/pull/851#issuecomment-2518931149

2025-01-30 10:24 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +
Edit: "The following instructions outline how to trigger a prerelease build of ACCESS-OM2 following modification of its MOM5 component. All other components of the official ACCESS-OM2 release will remain unchanged."

2025-01-30 10:25 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +
Edit: "The following instructions are valid (with simple tweaks) for all [ACCESS models]."

2025-01-30 10:33 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +    For models deployed to `Gadi`, join the `vk83` project, by requesting membership on the respective [vk83](https://my.nci.org.au/mancini/project/vk83/join) NCI project pages.
Remove comma and change pages to singular: "...project by requesting membership on the respective vk83 NCI project page."

2025-01-30 10:35 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +- **_Write_ permissions to the related Model Deployment Repository**
add line break <br> to move subsequent sentence to a new line

2025-01-30 10:38 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +## The model deployment repository
In the previous lines above you used caps for the "Model Deployment Repository". Why now the use of lowercase "The model deployment repository" in the section title?

2025-01-30 10:40 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +Every commit within the same PR triggers an isolated prerelease build deployment for the same PR (every PR can be seen as a separate development configuration for the model).<br>
Edit: "... for the same PR, i.e., every PR can be seen as a separate development configuration for the model."

2025-01-30 10:42 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +Although the structure of different model deployment repositories can slightly differ, their top-level will always contain:
Edit: "Although the structure of different model deployment repositories can differ slightly, their top-level will always contain a:"
- spack.yaml file
- config directory

2025-01-30 10:44 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +For more information on the `spack.yaml` file, refer to  [ACCESS-NRI's devdocs](https://github.com/ACCESS-NRI/dev-docs/wiki/Spack#the-spackyaml-file-spec-file).
Edit: change devdocs to DevDocs "... ACCESS-NRI's DevDocs"

2025-01-30 10:46 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +The `config` directory contains a single `versions.json` file. This file allows customisation of both the version of [`access-nri/spack`](https://github.com/ACCESS-NRI/spack) used to deploy the model
Edit: change packages to package "... will source _Spack_ package recipes."

2025-01-30 10:48 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +## Trigger a model pre/release build deployment
Edit: "Trigger a model prerelease or release build deployment"

2025-01-30 10:49 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +The sequence of tasks needed to trigger a pre/release build deployment for a new model feature is detailed below:
Edit: "... to trigger a prerelease or release build deployment..."

2025-01-30 10:58 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +The first step is to clone the model deployment repository and create a feature branch from its `main` branch, where the new features will be developed.
Edit: "... its `main` branch, on which new features will be developed."

2025-01-30 10:59 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +Then, modifications can be made to the `spack.yaml` or `config/versions.json` files as needed (e.g., update packages versions, add or change variants, etc.).<br>
Edit: "Modifications can then be made to the `spack.yaml` ..."

2025-01-30 11:02 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +After the modifications are made, commit the changes to the newly-created feature branch and push the changes upstream.
Edit: "After making the modifications, commit..."

2025-01-30 11:03 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +In this example, we will change ACCESS-OM2's [MOM5 component] (we will replace it with the version from [MOM5 `development` branch](https://github.com/ACCESS-NRI/MOM5/tree/development)).
Edit: "In this example, we will change ACCESS-OM2's MOM5 component by replacing it with..."

2025-01-30 11:07 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +To achieve this, we will:
Edit: "To achieve this, do the following steps:"

2025-01-30 11:09 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +1. Update the [version of the `mom5` package](https://github.com/ACCESS-NRI/ACCESS-OM2/blob/d907f3314a9956875baaaaf2b4d7b6be6fa81926/spack.yaml#L15) in the `spack.yaml` file with the new version (`@g
Edit: "... with the new version, i.e., `@git.development`."

2025-01-30 11:10 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +   This is particularly important before a PR gets merged, as this will determine the version tag for the model new release. The format is `CALVER_YEAR.CALVER_MONTH.MINOR`.<br>
Edit: "... particularly important before merging a PR as it will determine..."

2025-01-30 11:11 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +   For this example, we will update the overall version to `git.2024.03.1`.
Edit: "In this example, the overall version will be updated to..."

2025-01-30 11:12 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +After the modifications listed above, the output of the command
Edit: "Once completing the above modifications, the output..."

2025-01-30 11:13 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +To stage and commit the changes we can run:
Edit: "To stage and commit the changes, run:"

2025-01-30 11:14 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +Finally, we can push the changes upstream by executing:
Edit: "Finally, push the changes upstream by executing:"

2025-01-30 11:18 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +If we open a PR to the [ACCESS-OM2 deployment repository][om2 repo] with our `update_mom5_dev_build` branch as the *base*, we will get a [comment](https://github.com/ACCESS-NRI/ACCESS-OM2/pull/94#iss
Edit: "... we will get a comment. Once deployed, the prerelease build can be accessed ..."

2025-01-30 20:18 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +    Requires the commenter to have write permissions on the repository.
Edit: "...write permissions within the repository."

2025-01-30 20:28 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +This is most useful, for example, to trigger a new deployment when changes are made to a model dependency used by the model, without any changes occurring in the `HEAD` of the PR branch
Edit: "This is used to trigger a new deployment when changes are made to a model dependency, however no changes have occurred in the `HEAD` of the PR branch."

2025-01-30 20:30 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +`!bump major` bumps the model version to the next major version, formatted as `YEAR.MONTH.0`. Here `YEAR` and `MONTH` correspond to the current year and month when the comment is issued.<br>
Edit: "formatted as `YEAR.MONTH.0`, where `YEAR` and `MONTH` correspond to..."

2025-01-30 20:34 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +Let's take as example an open PR that has its overall model version set to `git.2024.06.2`.<br>
Edit: "For example, if we commented on an open PR that has its overall model version set to `git.2024.06.2` in Jan 2025 with `!bump major`, the overall..."

2025-01-30 20:37 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +If instead, we commented the PR with `!bump minor`, the overall model version would be bumped to `git.2024.06.3` (regardless of the comment date).
Edit: "If, however, we commented the PR with `!bump minor`, the overall model version would be bumped to `git.2024.06.3` regardless of the comment date."

2025-01-30 20:44 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +We then push the commits to the `update_mom5_dev_build` branch, open a PR to `main`, and we get a [successful deployment](#successful-deployment) of our ACCESS-OM2 _mom5-development_ build (version 1
Edit: "... the `update_mom5_dev_build` branch and open a PR to `main`, resulting in a [successful deployment](#successful-deployment) of our ACCESS-OM2 _mom5-development_ build (version 1)."

2025-01-30 20:45 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +Now, if we want to test these new MOM5 changes, we would have to redeploy the latest commit in the `update_mom5_dev_build` branch to reflect the updates to the MOM5 `development` branch.<br>
I would remove `<br>` here as the next sentence follows the previous.

2025-01-30 20:47 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +Since the `HEAD` of the `update_mom5_dev_build` did not change, instead of having to create a new "redundant" commit only to trigger the prerelease deployment, we can comment `!redeploy` in the `upda
Again, I would remove <br> here as the next sentence follows the previous.

2025-01-30 20:49 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +As a result, we will get a new separate deployment of the ACCESS-OM2 _mom5-development_ build (version 2).
Edit: "As a result, a new separate deployment of the ACCESS-OM2 _mom5-development_ build (version 2) is produced."

2025-01-30 20:51 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +    It is up to the user to monitor the state of each dependency's `git` branch listed in the `spack.yaml` file before using a `!redeploy` _Comment Command_. The CI/CD pipeline does not perform any c
Edit: "The user should monitor the state..."

2025-01-30 20:56 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +The `main` branch of a model deployment repository reflects the most up-to-date changes to the model and is always at the same level or ahead of the model latest major release.<br>
Edit: "The `main` branch of a model deployment repository reflects the most up-to-date changes to the model. Hence, it is always at the same level or ahead of the model's latest major release."

2025-01-30 20:59 UTC, heidinett commented on docs/models/run-a-model/create-a-prerelease.md
> +3. Open a PR off the `backport/2023.11` branch with the fixes.<br>
Edit: "Open a PR from the `backport/2023.11` branch..."

2025-01-30 21:04 UTC, heidinett reviewed
Looks good @atteggiani. I have made some suggestions that I think improve the readability. Feel free to adopt or ignore.
I also noticed that in the blue warning box at the top of the page, which also appears at the top of other run-a-model pages, that there is inconsistent use of the word "code-block" / "code block". I would go with "code block" as two separate words.

2025-01-30 22:36 UTC, atteggiani commented on docs/models/run-a-model/create-a-prerelease.md
> +The `config` directory contains a single `versions.json` file. This file allows customisation of both the version of [`access-nri/spack`](https://github.com/ACCESS-NRI/spack) used to deploy the model
I changed to "that will source the recipes for the Spack packages."

2025-01-30 22:38 UTC, atteggiani commented on docs/models/run-a-model/create-a-prerelease.md
> +## Trigger a model pre/release build deployment
Changed to "Trigger model prerelease and release build deployments"

2025-01-30 23:42 UTC, merged

2025-01-30 23:43 UTC, atteggiani commented
Thank you for the precious review @heidinett! 
Most of your suggestions were added in!

And thank you to @CodeGat for starting this PR and reviewing the changes.

Merged.