ACCESS-RAM3: Quick start guide (issue #841)
ACCESS-NRI/access-hive.org.au pull request #857
Opened 2024-12-10 05:31 UTC by heidinett

Quick start guide for running ACCESS-RAM3 for alpha release testing 

Fixes #841

2024-12-11 02:54 UTC, flicj191 requested changes

2024-12-11 02:54 UTC, flicj191 commented on docs/models/run-a-model/run-access-ram.md
```suggestion
# Run {{ model }}
```

2024-12-11 02:54 UTC, flicj191 commented on docs/models/run-a-model/run-access-ram.md
> +# Quick Start
```suggestion
## Quick Start
```

2024-12-11 02:54 UTC, flicj191 commented on docs/models/run-a-model/run-access-ram.md
> +# Detailed Guide
```suggestion
## Detailed Guide
```

2024-12-11 02:54 UTC, flicj191 commented on docs/models/run-a-model/run-access-ram.md
> +* * *
```suggestion
!!! tip
    You've completed the quick reference steps! For more comprehensive instructions keep reading below.
```
Could use something like this to break up the sections on the page? feel free to delete

2024-12-11 02:54 UTC, flicj191 commented on docs/models/run-a-model/run-access-ram.md
> +[:fontawesome-brands-github:{: class="twemoji icon-before-text"} {{ model }} configuration]({{github_configs}}){: class="text-card"}
I would move this config card above the info note above so that the info note appears just above the page title. 
And the note about the code blocks that you mentioned in todays meeting automatically comes up on the page because there are terminal animations on the page, probably best to leave it there.

2024-12-11 02:55 UTC, flicj191 requested changes
Suggestions to fix the hierarchy of the headings so that the navigation on he right can show the sub-headings

2024-12-11 03:20 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +[:fontawesome-brands-github:{: class="twemoji icon-before-text"} {{ model }} configuration]({{github_configs}}){: class="text-card"}
Thanks @flicj191! I moved the config card as you suggested. 
Re: note about code block, it would be great if I could place it in the Detailed guide (at the moment it's in the Quick Start where there are no terminal animations).

2024-12-11 03:24 UTC, flicj191 commented on docs/models/run-a-model/run-access-ram.md
> +[:fontawesome-brands-github:{: class="twemoji icon-before-text"} {{ model }} configuration]({{github_configs}}){: class="text-card"}
Looks like its automatically set to appear under the page heading, that's why I've added a page heading and changed others to subheadings in the suggestions above. I guess a hack right now would be to make detailed guide the page heading, then all the headings before that wouldn't appear in the page navigation

2024-12-11 03:29 UTC, flicj191 commented on docs/models/run-a-model/run-access-ram.md
> +[:fontawesome-brands-github:{: class="twemoji icon-before-text"} {{ model }} configuration]({{github_configs}}){: class="text-card"}
You can commit the ones you want from above from the files tab in a batch. moving the config card without the added page title wouldn't put the name note above the page title

2024-12-11 23:20 UTC, engelca commented
The major comment relates to how persistent sessions work with the RAS/RNS.
In the RAS/RNS you currently have to ssh -Y directly into the persistent session to run the suite.
The suite can be edited thought via a non-persistent session.
To run from *within* a persistent session, I do the following:

1. ls ~/.persistent-session/   to get the <persistent-session> name
2. ssh -Y <persistent-session>
3. module use /g/data/hr22/modulefiles
4. module load cylc7
5. cd roses
6. cd <suite-directory>
7. rose suite-run

In the Quickstart for both the RAS and RNS after taking the chekout/copy of the suite, the users needs to manually change into the suite directory prior to any further commands.

In the "Specify target persistent session" section.  This doesn't work for me.  I did do it but the rose suite-run command will crash.  It only works from within the persistent-session.  We need to either remove this section or edit the rose/cylc suite so the cylc-session file works.

In RAS/"Run the suite". again I can't run from a non-persistent session so I do the steps above first.

In RAS/"Monitor the suite runs".  The text says two main ways but only the GUI way is listed.  The second way is through the file system.  The users have not been told of this option or where to look for the output files.  The file locations are non-trivial, i.e. <output directory>/<user>/cylc-run/<suite-id>/log/job/<cycle-date>/<job-name>/<run-number; usually 01 unless repeated>.

In RAS/"Edit the RAS configuration".  There is a type "congiguration".

In RAS/"Change the region centre and name".  The video is not showing (I did record one and upload it though ...)

In RNS/"RNS output files".  The subdirectories (ics, lbcs, and um)  are not being shown in a list.  And another typo "scienc_choice".

In RNS/"Edit the RNS configuration".  The "Rose GUI" link goes to the RAS specific example not to the "rose edit &" command above it.

2024-12-13 03:54 UTC, engelca approved these changes

2025-02-05 23:50 UTC, atteggiani requested changes
This PR is now the Hive Docs documentation for the beta release (and future `1.0` release) of the regional model.

I reintegrated a few portions (`About`, `references`, etc.) and adjusted a few minor things (please see my commits starting from [525eb0fe18722963483a596c38ae433813d02a36](`https://github.com/ACCESS-NRI/access-hive.org.au/pull/857/commits/525eb0fe18722963483a596c38ae433813d02a36) for details) for consistency with the other "How to run" pages.

I added my review, listing both the comments in my previous version of the documentation (the ones that I had marked with a `TODO` within the code), and other additional comments (please refer to the related comments for details).
This will make it easier to add further reviews to this PR and commenting to the specific portions/comments with ideas and suggestions.

2025-02-05 23:50 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Use the same names for `nested_region` `science_choice` and `nest_name` as the one used above for the RAS and make sure all of the are referenced in the RAS and there are clear instructions on h
```suggestion
The RNS output data can be found in the `/scratch/$PROJECT/$USER/cycl-run/<suite-ID>/share/cycle` directory, grouped for each [cycle](#change-run-length-and-cycling-frequency).<br>
Within the cycle directory, outputs are divided into multiple nested subdirectories in the format `<nested_region>/<science_choice>/<nest_name>`, with [nested_region](<LINK>), [science_choice](<LINK>) and [nest_name](<LINK>) referring to the respective configurable options in the [RAS](#edit-the-ras-configuration).

Each of the `<nest_name>` directory has the following subdirectories:

- `ics` &rarr; initial conditions
- `lbcs` &rarr; lateral boundary conditions
- `um` &rarr; model output data
```

Use the same names for `<nested_region>` `<science_choice>` and `<nest_name>` as the one used above for the RAS and make sure all of them are referenced in the RAS and there are clear instructions on how to modify them. Make sure `<LINK>` is substituted with the proper link to the related portion/paragraph of the RAS.

There is no reference to how to change the `science_choice`, it would be good to add instructions. If it cannot be changed, I would maybe call it in a different way.

2025-02-05 23:50 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- I couldn't restructure this title/text because from them I am not really understanding what `NCI_STORAGE` is. From its default value in the rose-suite.conf (scratch/$PROJECT) and how it's used i
```suggestion
#### Change where the output from run is stored project
To change where the output from the model run is stored, edit the _NCI_STORAGE_ field in _suite conf &rarr; Nesting Suite &rarr; General run options _, and click the _Save_ button ![Save button](/assets/run_access_cm/save_button.png){: style="height:1em"}. 
```
I am not sure what `NCI_STORAGE` is. From its default value in the `rose-suite.conf` (`scratch/$PROJECT`) and how it's used inside the suite, it seems to be a project folder added to the `storage` option for the PBS jobs submission of multiple tasks. Therefore, is not necessarily related to model outputs but also related to model input. 
 I would say in general is related to filesystem mounts that the model need to be able to access.
 Why is the text mentioning changing where the output is stored?

2025-02-05 23:50 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Are there any other options more specific to the RNS that users may want to change here? -->
```suggestion
To modify these parameters, navigate to _suite conf &rarr; Nesting Suite &rarr; Cycling options_, edit the `INITIAL_CYCLE_POINT`, `FINAL_CYCLE_POINT` and the `CYCLE_INT_HR` fields (using [ISO 8601 Duration](https://en.wikipedia.org/wiki/ISO_8601#Durations) format) and click the _Save_ button ![Save button](/assets/run_access_cm/save_button.png){: style="height:1em"}.
```
Are there any further options specific to the RNS, that users may want to change, that could be added here?

2025-02-05 23:50 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Check and change link details if needed -->
```suggestion
## Get Help
If you have questions or need help regarding {{ model }}, consider creating a topic in the ........ category of the ACCESS-Hive Forum](<LINK>).<br>
For assistance on how to request help from ACCESS-NRI, follow the [guidelines on how to get help](/about/user_support/#still-need-help).
```
Add the right forum category with the `<LINK>`.

2025-02-06 00:53 UTC, heidinett commented on docs/models/configurations/access-ram.md
> +<!-- Create the model overview page for ACCESS-RAM. Refer to the ACCESS-ESM1.5 one for an example. -->
@engelca  Could you please comment on how our ACCESS-NRI RAM3 configuation differs from the UKMO RNS.
Perhaps users need to know that there is a different config option using an existing executable instead of building the model, and that python scripts exist.

2025-02-06 01:11 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Add short description of what the RAS does -->
This is a bug that was created by putting the two separate mark-up files I had created into one.

In my branch the model and suite variables were defined at the top of the file.  The Markup then filled in the variables when the website was displayed.

The description of what the RAS and RNS did was also included in my original branch.  Please copy from there.

2025-02-06 01:41 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Add short description of what the RAS does -->
Those variables get filled in by the markup when it is run.

The description for the RNS was included in my original branch.

2025-02-06 01:42 UTC, engelca commented on docs/models/configurations/index.md
> +                ACCESS-RAM -- add text here. Also add correct image.
This was included separately in the RAS and RNS descriptions in my branch.  Maybe they can be combined here.

2025-02-06 01:43 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Can we put a configuration here taken from MOSRS instead of GitHub? SVN? -->
They would need to be two separate links to MOSRS.  The ones listed would be the right ones.

2025-02-06 01:46 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +{{ model }} is an ACCESS-NRI-supported configuration of the [UK Met Office](https://www.metoffice.gov.uk/) Regional Nesting Suite. Driven by ERA5, the configuration comprises a 2-level nest; the oute
I think that some people may not read the overview page.  If you want to move all the information there it would be worthwhile reminding them to look at the overview page for specific details.
In a bigger picture though these details are specific to the Lismore example not to using the RAS/RNS as users could change those options.

2025-02-06 01:51 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- There is no information before about nests (e.g., nest structure, what is the difference between nested region name and nest name, etc.) It would be good to add something in the suite descriptio
The instructions are generic.  The naming in the given example is specific to a given example and would most likely be immediately changed by the user.  i.e. most users will immediately change the example from Lismore rainfall to what they want.  It might be good if they can still refer to the run-a-model if they forget something later on.

2025-02-06 01:54 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Why in a two-level nest there are three nests? This passage is not clear. -->
The era5 level nest is purely for the cutting out and reconfiguring of the ERA5 driving model data.  (It is need to run the setup but does not affect the number of nests used in the actual forecast).
The other two relate to the actual nests that a forecast/project will be run on.

2025-02-06 01:55 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Are the namelists always produced? What are they produced for? Do we need to mention namelists as well here? Are the namelists Fortran namelists? In case I would specify it (if we decide to ment
This text was intended to just inform the users the format of the files produced by the ancillary suite.  The answer being that they are in UM FF format.  It not related to namelists.

2025-02-06 01:58 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Is this a set of coordinates? It would be good to be more specific here. -->
Yes.  The GUI requests the central latitude/longitude of the group of ancillaries being produced.  This part of the RAS instructions was help users change the central point of the domain.  A screenshot of the GUI may be more useful here but not strictly necessary.

2025-02-06 02:01 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Are there any more parameters that can be set here? For example the extents of the different nests, etc... ? -->
This was a simple example.  
We can give other sets of instructions for modifying the number of pixels if required.
There are many details that can be changed.

2025-02-06 02:02 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Can we add a link for the Lismore Flood example? Anything that makes it a bit clearer what that is. -->
We don't have any ACCESS-NRI produced material produced relating to the example.  It may make sense to create a separate website with the input/output explained.

2025-02-06 02:03 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +-->
This was not commented out on my branch.

2025-02-06 02:08 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Replace with a RAS video/gif -->
It could be copied from /assets/run_access_cm/Cylc_GUI.png but it may still need to be edited.

2025-02-06 02:09 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Replace with a RAS video/gif -->
It could be copied from /assets/run_access_cm/investigate_error_gui_are.gif but may need to made specific to this example.

2025-02-06 02:10 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Change image with a RAS one -->
This could be copied from /assets/run_access_cm/Rose_GUI.png but may need to be made specific to this example.

2025-02-06 02:12 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Add a gif/video for the exmple -->
This asset exists in my /assets/run_access_ras/ras_edit_region_center_and_name.gif but please note the RAS not RAM naming.  It was from when I have divided the text into ancillaries and forecast/projection.

2025-02-06 02:15 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Use the same names for `nested_region` `science_choice` and `nest_name` as the one used above for the RAS and make sure all of the are referenced in the RAS and there are clear instructions on h
By default the RNS puts data into directories named with a convention naming the science choice.

Changing the science choice has implications beyond a "introductory simple guide".  Perhaps we should note that it is out of scope for the "run-a-model" guide.

2025-02-06 02:18 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- I couldn't restructure this title/text because from them I am not really understanding what `NCI_STORAGE` is. From its default value in the rose-suite.conf (scratch/$PROJECT) and how it's used i
The NCI_STORAGE impacts where the user wants the output of their runs to be stored.
It is mentioned to given an example of changing where the output from the run is stored.

2025-02-06 02:27 UTC, atteggiani commented on docs/models/configurations/access-ram.md
> +<!-- Create the model overview page for ACCESS-RAM. Refer to the ACCESS-ESM1.5 one for an example. -->
@engelca Could you please address this comment? 
In addition to what heidi mentioned, I think the overview page should have content about any information that we would like to provide about the configuration, so that we can link to this overview page also within the "How to run page", without having redundant information in the latter.

2025-02-06 02:27 UTC, atteggiani commented on docs/models/configurations/index.md
> +            <img src="/assets/model-config-logos/configurations-without-titles/access-om.png" class="white-background img-contain"></img>
@ACCESS-NRI/webops will take care of this.

2025-02-06 02:28 UTC, atteggiani commented on docs/models/configurations/index.md
> +                ACCESS-RAM -- add text here. Also add correct image.
Can you please link the specific content you are referring to or, maybe better, write a comment below with the "combined" content you are suggesting?

2025-02-06 02:29 UTC, atteggiani commented on docs/models/run-a-model/index.md
> +            <img class="img-contain with-padding white-background" src="/assets/model-config-logos/globe_visualisation/access_om_globe_visualisation.png" alt="ACCESS-RAM">
@ACCESS-NRI/webops will take care of this.

2025-02-06 02:29 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Can we put a configuration here taken from MOSRS instead of GitHub? SVN? -->
Ok I'm going to add those links. Thank you!

2025-02-06 03:11 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Can we put a configuration here taken from MOSRS instead of GitHub? SVN? -->
Added in [b058fa7686af11e2f9d953b5ad03a3f5398e3fc5](https://github.com/ACCESS-NRI/access-hive.org.au/pull/857/commits/b058fa7686af11e2f9d953b5ad03a3f5398e3fc5).

2025-02-06 03:12 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +The instructions below outline how to run {{ model }} using ACCESS-NRI's software deployment pipeline, specifically designed to run on the [National Computating Infrastructure (NCI)](https://nci.org.
@engelca any thoughts on this?

2025-02-06 03:12 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +All {{model}} configurations are open source, licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1")![CC icon](https://mirrors.creativecommons.org/presskit/icons/cc.
@engelca @aidanheerdegen 
Any information about the License?

2025-02-06 06:11 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- I couldn't restructure this title/text because from them I am not really understanding what `NCI_STORAGE` is. From its default value in the rose-suite.conf (scratch/$PROJECT) and how it's used i
Looking at the RNS (`u-dg768`) I can only see `NCI_STORAGE` being added to the `pbs` `storage` option for different tasks, but I cannot see any part that link it to the experiment output.
I can see `NCI_STORAGE_TOP_DIR` used to provide an env variable to the `ARCHIVE` task (which might define where the output is being stored).

Can you please point me to a portion of the RNS suite where there is link between the `NCI_STORAGE` variable and the output of the run?
Thank you

2025-02-06 06:11 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Are there any other options more specific to the RNS that users may want to change here? -->
@chermelle 
This is related to another comment above, about the configuration options that we want to include in the instructions.
I think whatever configuration options we decide to detail in the instructions, we might want to add the options specific to the RNS here.

2025-02-06 06:11 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Check and change link details if needed -->
@ACCESS-NRI/webops can take care of this, once there is a Forum post of the release.

2025-02-06 06:33 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +--->
I updated the example with `echo` command instead of `cat` for simplicity (see comment above `<!-- Updated example with echo command instead of cat`). I then commented out the animation as it used `cat` and forgot to update and reinstate it. Sorry @atteggiani!

2025-02-11 01:08 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Add short description of what the RAS does -->
The definition of the model and suite-id for RAS variables were defined here:

https://github.com/ACCESS-NRI/access-hive.org.au/blob/7a7f4efb17a3109eb63722bfd36f83574e507c5e/docs/models/run-a-model/run-access-r-ras.md?plain=1#L1

The definition of the model and suite-id for the RNS variables were defined here:

https://github.com/ACCESS-NRI/access-hive.org.au/blob/7a7f4efb17a3109eb63722bfd36f83574e507c5e/docs/models/run-a-model/run-access-r-rns.md

2025-02-11 01:24 UTC, engelca commented on docs/models/configurations/index.md
> +                ACCESS-RAM -- add text here. Also add correct image.
The[ ](https://github.com/ACCESS-NRI/access-hive.org.au/tree/7a7f4efb17a3109eb63722bfd36f83574e507c5e/docs/models/run-a-model) branch was started from a copy of https://access-hive.org.au/models/run-a-model/run-access-cm/.

I will do an About version similar to the one in https://access-hive.org.au/models/run-a-model/run-access-esm/.

I suggest that the run-access-cm branch is updated as well.

2025-02-11 01:29 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +The instructions below outline how to run {{ model }} using ACCESS-NRI's software deployment pipeline, specifically designed to run on the [National Computating Infrastructure (NCI)](https://nci.org.
The python scripts are coming from the ACCESS-NRI software deployment pipeline but they are a component of the suite.  I would change the wording to "using ACCESS-NRI's supported configuration specifically designed to run on ..."

2025-02-11 01:38 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- There is no information before about nests (e.g., nest structure, what is the difference between nested region name and nest name, etc.) It would be good to add something in the suite descriptio
I don't really understand how the "generic" information is going to fit into the overview page.

By the overview page are you meaning something like: https://access-hive.org.au/models/configurations/access-esm/#model-components?

"What is nesting" doesn't seem to fit there.

2025-02-11 01:42 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +{{ model }} is an ACCESS-NRI-supported configuration of the [UK Met Office](https://www.metoffice.gov.uk/) Regional Nesting Suite. Driven by ERA5, the configuration comprises a 2-level nest; the oute
The nesting strategy outlined here (based on the Lismore example) only applies to that example.  Users may quickly deviate from that setup.

The information needs to go somewhere but it may not fit in the overview page (if by overview you mean something like https://access-hive.org.au/models/configurations/access-esm/#model-components).

2025-02-11 01:48 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Why in a two-level nest there are three nests? This passage is not clear. -->
I would keep it simple as:

Lismore/era5  # the directory holding data cut out of from the (global) driving era5 data prior to reconfiguration onto the first level of the nest (slightly larger than the first level domain to create lateral boundary conditions as well as initial conditions from).

Lismore/d1000 # the directory holding data from first level of the nest (10km in this era5-land example).

Lismore/d0198 # the directory holding data from finest level nest.

2025-02-11 01:49 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Is this a set of coordinates? It would be good to be more specific here. -->
I would have to see it marked up to comment.

2025-02-11 01:51 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- I couldn't restructure this title/text because from them I am not really understanding what `NCI_STORAGE` is. From its default value in the rose-suite.conf (scratch/$PROJECT) and how it's used i
The NCI_STORAGE refers to the User Interface of the rose gui.

2025-02-11 04:01 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +The instructions below outline how to run {{ model }} using ACCESS-NRI's software deployment pipeline, specifically designed to run on the [National Computating Infrastructure (NCI)](https://nci.org.
Changed in [8c045bb4fabb160d045af6384ac9d49b7444209c](https://github.com/ACCESS-NRI/access-hive.org.au/pull/857/commits/8c045bb4fabb160d045af6384ac9d49b7444209c)

2025-02-11 04:19 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +{{ model }} is an ACCESS-NRI-supported configuration of the [UK Met Office](https://www.metoffice.gov.uk/) Regional Nesting Suite. Driven by ERA5, the configuration comprises a 2-level nest; the oute
If this information is only relevant to the specific example used in the `How to run page` (Lismore experiment), then I would add it within the About section, but I would move it after the paragraph:

> The instructions below outline how to run {{ model }} using ACCESS-NRI's supported configuration, specifically designed to run on the [National Computating Infrastructure (NCI)](https://nci.org.au/about-us/who-we-are) supercomputer [_Gadi_][gadi].

We could then spend a few more words about the "instructions below", mentioning the specific experiment (Lismore) that is going to be referenced and giving a few more details about its configuration. 

What about:

... specifically designed to run on the [National Computating Infrastructure (NCI)](https://nci.org.au/about-us/who-we-are) supercomputer [_Gadi_][gadi].<br>
As an example, an experiment modelling the [Lismore flood event](<link to the Lismore flood event>) will be run, having the following configuration:
- initial and lateral boundary conditions driven by ERA5 data
- 2-level [nest](<link to the "nesting" paragraph within the model overview page>):
  - An outer nest that uses GAL9 (n.d.r would be good to provide a link to GAL9, because we have never mentioned it here) with a 10km horizontal resolution.
  - An inner nest that focuses on the region of interest using RAL3.2 (n.d.r. same with GAL9, I would provide a link here) with a 2.2 km horizontal resolution.

2025-02-11 04:43 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Add short description of what the RAS does -->
Sorry, but I cannot find any description of the `RNS` in the pages that you linked.

Can you please add a short paragraph in a comment below, with a suitable description of the `RNS` that can be used in this portion of the documentation? Thank you.

2025-02-11 04:51 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- There is no information before about nests (e.g., nest structure, what is the difference between nested region name and nest name, etc.) It would be good to add something in the suite descriptio
@chermelle The page you referenced is only an example to get started, but it can definitely be amplified and more paragraphs can be added depending on the specific pieces of information we want to provide.
A paragraph on "what is nesting" could be a suitable addition.

I will list below the pieces of information that I think is missing here and it might be important for a user:
- information about nesting (what it means and why is it necessary)
- information about the nesting structure within ACCESS-RAM (what can be changed related to nesting within the configuration? what are the variables that control those changes? How does that relate to the naming of outputs?

2025-02-11 05:12 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Why in a two-level nest there are three nests? This passage is not clear. -->
Changes added in [297fc9e0644f2f79556420e069369b4b5a462679](https://github.com/ACCESS-NRI/access-hive.org.au/pull/857/commits/297fc9e0644f2f79556420e069369b4b5a462679)

2025-02-11 05:19 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Is this a set of coordinates? It would be good to be more specific here. -->
Changed it in [508631c6e9ffa60ce26788a28b47cb8d4e9c1c85](https://github.com/ACCESS-NRI/access-hive.org.au/pull/857/commits/508631c6e9ffa60ce26788a28b47cb8d4e9c1c85).

Feel free to view it through the PR preview and comment within the code for other suggestions.

2025-02-11 06:07 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- I couldn't restructure this title/text because from them I am not really understanding what `NCI_STORAGE` is. From its default value in the rose-suite.conf (scratch/$PROJECT) and how it's used i
The User Interface refers to variables used within the suite configuration files.

In the Rose GUI metadata description file `rose-meta.conf`, `NCI_STORAGE` is described as:
> Extra storage mounts (e.g. "gdata/a12+scratch/cd3")
> Additionally gdata/access will always be added

There is no mention to the outputs.

Based on the `rose-meta.conf` file and the `suite-adds.rc` files, `NCI_STORAGE` doesn't seem to be connected to any output.
A variable that might be connected to the output archiviation location is, instead, `NCI_STORAGE_TOP_DIR`.

2025-02-11 06:41 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Add short description of what the RAS does -->
The suite-id was defined in the line underneath.
i.e.
https://github.com/ACCESS-NRI/access-hive.org.au/blob/7a7f4efb17a3109eb63722bfd36f83574e507c5e/docs/models/run-a-model/run-access-r-ras.md?plain=1#L2

2025-02-11 06:43 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- There is no information before about nests (e.g., nest structure, what is the difference between nested region name and nest name, etc.) It would be good to add something in the suite descriptio
As discussed in the team meeting today, I will add a brief outline but reference the UKMO RAL paper - specifically RAL1 for beginners to look at.

2025-02-11 06:47 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Add short description of what the RAS does -->
The suite id was defined here:

https://github.com/ACCESS-NRI/access-hive.org.au/blob/7a7f4efb17a3109eb63722bfd36f83574e507c5e/docs/models/run-a-model/run-access-r-rns.md?plain=1#L2

and this short suitable description followed the ones from ACCESS-CM

https://github.com/ACCESS-NRI/access-hive.org.au/blob/7a7f4efb17a3109eb63722bfd36f83574e507c5e/docs/models/run-a-model/run-access-r-rns.md?plain=1#L150

2025-02-11 06:50 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Are there any other options more specific to the RNS that users may want to change here? -->
I think this is best handled by showing a screenshot of the rose UI or just letting the user view it if there are licensing issues.

2025-02-11 07:11 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Add short description of what the RAS does -->
Sorry, my message was not clear.

The main issue here is not related to the RAS suite id. 
The content that is needed is a short introduction about the RAS (what it is, what it does, etc.).

Could you please provide that?

2025-02-11 07:12 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- There is no information before about nests (e.g., nest structure, what is the difference between nested region name and nest name, etc.) It would be good to add something in the suite descriptio
That sounds good. 
That paragraph will be placed in the "model overview" page and referenced (linked) here.

2025-02-11 07:19 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Add short description of what the RAS does -->
Sorry, my message was not clear.

The main issue here is not related to the RNS suite id.

The information about the components you referenced is good, but I would add a more general introduction about what the RNS is, what it does, etc.

2025-02-11 22:17 UTC, engelca commented on docs/models/run-a-model/run-access-ram.md
> +{% set suite = "u-dg767" %}
"{% set suite = "u-dg767" %} should be no longer needed due to ras_id and rns_id being available.

2025-02-12 00:03 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +{% set suite = "u-dg767" %}
Good point! 
Removed in [0e840f69e1dec91021fc50059b3e6a93f4fe0345](https://github.com/ACCESS-NRI/access-hive.org.au/pull/857/commits/0e840f69e1dec91021fc50059b3e6a93f4fe0345)

2025-02-18 02:52 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +{{ model }} comprises a [Regional Ancillary Suite (RAS)](#ras) (RAS) `{{ ras_id }}` to generate ancillary files needed to run the [Regional Nesting Suite (RNS)](#rns) `{{ rns_id }}` for the domain of
Edit: remove duplicate "(RAS)"

2025-02-18 05:00 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +A description of the model and its components is available in the [ACCESS-RAM3 overview][model configurations].
Edit: "ACCESS-RAM is an ACCESS-NRI supported implementation of the [Unified Model (UM)](https://www.metoffice.gov.uk/research/approach/modelling-systems/unified-model) regional nesting suite for high-resolution regional atmosphere modelling on _Gadi_. A description of the model and its components is available in the [ACCESS-RAM3 overview](https://access-hive.org.au/models/configurations/access-ram/#access-ram3)."

2025-02-18 05:02 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +The instructions below outline how to run {{ model }} using ACCESS-NRI's supported configuration, specifically designed to run on the [National Computating Infrastructure (NCI)](https://nci.org.au/ab
Repetitive mention of Gadi (also mentioned in description above).

2025-02-18 05:04 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +If you are unsure whether {{ model }} is the right choice for your experiment, take a look at the overview of [ACCESS Models](/models).
I would delete the above sentence as it is not difficult to find an overview of ACCESS models from the above link to more ACCESS-RAM model detail.

2025-02-18 05:05 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +{{ model }} release notes are available on the ACCESS-Hive Forum and are updated when new releases are made available.
Perhaps include a link to ACCESS-Hive Forum

2025-02-18 05:22 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    For example, if your {{ model }} simulation requires data stored in `/g/data/tm70` and `/scratch/w40`, the following should be added to the minimum storage above: `+gdata/tm70+scratch/w40`
Instead of tm70 and w40 projects, I would use gx60 Atmsophere Working group project in this example, i.e., `/g/data/gx60` and `/scratch/gx60`

2025-02-18 05:29 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    After specifying the {{ model }} target persistent session the first time, to run {{ model }} you just need to make sure to have an active persistent session named like the specified {{ model }}
Edit: "... should be done only once. Then, to run {{ model }} you just need to check that you have an active persistent session named like the target one you specified above."

2025-02-18 05:31 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +To run {{ model }}, access to multiple softwares and the Met Office Science Repository Service (MOSRS) is needed.
Edit: plural of software is "software" (i.e. delete the "s")

2025-02-18 05:41 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +For more information on {{ model }} configuration, check [{{model}}][model configurations] page.
Edit: "For more information on ACCESS-RAM, refer to the model configuration page."

2025-02-18 05:43 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +To run the RAS run the following command from within the [suite directory](#suitedir):
Edit: "To run the RAS, execute the following command from within..."

2025-02-18 05:47 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +The RAS output ancillary files can be found in `/scratch/$PROJECT/$USER/cylc-run/<suite-ID>/share/data/ancils`. The ancillaries are divided for each nested region, with each of the region subdivided
Edit: "... nests' names."

2025-02-18 05:49 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +In addition to the chosen nests, a subdirectory named according to the driving model data can be found within the `nested_region_name` directory.<br>
Edit: "In addition to these nests,..."

2025-02-18 05:58 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +The example above has one `nested_region_name` called `Lismore`, with a 2-level nest (2 nests) named `d1000` (outer nest) and `d0198` (inner nest), driven by ERA5 data.
Edit: "The 2-level (i.e., two nests) example above has one `nested_region_name` called `Lismore`. Driven by ERA5 data, the outer and inner nests are named `d1000` and `d0198`, respectively, "

2025-02-18 06:00 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +As a consequence, within the ancillary files directory `/scratch/$PROJECT/$USER/cylc-run/<suite-ID>/share/data/ancils/` the following folders will be present:
Edit: "Thus, the ancillary files directory `/scratch/$PROJECT/$USER/cylc-run/<suite-ID>/share/data/ancils/` contains the following folders:"

2025-02-18 06:02 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    Unless you are a very expert user, directly modifying configuration files is usually discouraged to avoid incurring in errors.
Edit: "Unless you are an experienced user, direct modification of configuration files is discouraged to avoid errors."

2025-02-18 06:05 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +{{model}} is a regional model that can perform simulations for a specific region on Earth.
Edit: "In ACCESS-RAM, it is possible to change the name and centre of the specified region."

2025-02-18 06:06 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +In `{{ras_id}}` these prameters are set by default to the *Lismore Flood* example.
Typo: "parameters"

2025-02-18 06:07 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Add a gif/video for the exmple -->
This still needs work.

2025-02-18 06:08 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +Steps to get and run the RNS configuration, as well as monitoring the runs, are analogous to those listed above for the [RAS](#ras).<br>
Replace "get" with "obtain"

2025-02-18 06:10 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +Each of the `<nest_name>` directory has the following subdirectories:
Edit: "Each `<nest_name>` directory..."

2025-03-18 01:24 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-ram.md
> +All {{model}} configurations are open source, licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1")![CC icon](https://mirrors.creativecommons.org/presskit/icons/cc.
For any of the UKMO licensed suites this isn't correct. They're not open and they're not stored on GitHub. Is there any licensing information in the suites or on MOSRS?

2025-03-18 01:31 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-ram.md
> +[![Met Office](/assets/met_office_logo.png){: class="icon-before-text  white-background"} RNS configuration]({{mosrs_config_rns}}){: class="text-card"}
Is there a way to make these smaller? And also potentially put them on the same line? On a laptop screen they really dominate.

<img width="1492" alt="Screenshot 2025-03-18 at 12 29 51 pm" src="https://github.com/user-attachments/assets/59d0638c-7a99-4c13-b007-38e941d14ad2" />

Arguably it should also be possible to change to just "Release Notes" as the model is implied.

2025-03-18 01:40 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-ram.md
> +# Run {{ model }}
Not sure where it is injected, but the info panel for the code block stuff is a bit intrusive right at the top of the docs IMO.

Could we move it down to the part where the code blocks are first used? I guess the Quick Start Guide?

2025-03-18 22:26 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +[![Met Office](/assets/met_office_logo.png){: class="icon-before-text  white-background"} RNS configuration]({{mosrs_config_rns}}){: class="text-card"}
Yes, I think all on the same line might not be idea (if they are 3 or more), but their size can definitely be reduced and their layout set so that they occupy one line if they are `<=2` and more line if they are `>2`.

Also changing it to "Release notes" makes sense.
I will also add the same "Release notes" card for the other released models (ACCESS-OM and ACCESS-ESM).

I will address this.

2025-03-18 22:26 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +# Run {{ model }}
I agree it's a bit intrusive. 
Not sure if placing it where the code bocks are first used is a good solution though. 

How about making it a tooltip that pops up only when the little terminal icon at the right of the page title (the one you can click to toggle animations) is hovered over?

2025-03-20 02:21 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +<!-- Replace image with RAS one -->
At the moment these animation will not be included.

2025-03-24 03:31 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +[![Met Office](/assets/met_office_logo.png){: class="icon-before-text  white-background"} RNS configuration]({{mosrs_config_rns}}){: class="text-card"}
Addressed in [5f944801f852fdb54f91408d15a17c158eaf5268](https://github.com/ACCESS-NRI/access-hive.org.au/pull/857/commits/5f944801f852fdb54f91408d15a17c158eaf5268)

2025-03-25 05:05 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +# Run {{ model }}
Fixed in #906.

2025-03-25 06:42 UTC, aidanheerdegen commented on docs/models/run-a-model/run-access-ram.md
> +    From within the RAS directory:
I think it would be better to be **very explicit** which is possible in this case as we're talking about a specific suite, e.g.
```
cd ~/cylc-run/u-dg767
suite run
```

2025-03-26 22:16 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +    From within the RAS directory:
Changed to 
```
cd ~/roses/u-dg767
rose suite-run
```
in [fc78870c53f57ac78d91d816844fb3daa06ea1ed](https://github.com/ACCESS-NRI/access-hive.org.au/pull/857/commits/fc78870c53f57ac78d91d816844fb3daa06ea1ed)

2025-03-28 01:01 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +{{ model }} comprises two suites: a [Regional Ancillary Suite (RAS)](#ras), which generates ancillary files (i.e.: input files), and a [Regional Nesting Suite (RNS)](#rns) which runs the regional for
edit: change to "... which generates ancillary (input) files, and a ..."

2025-03-28 01:38 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +As an example, an experiment modelling a flood event in Lismore (NSW) will be run, using `ERA5-Land` [land-surface initial conditions]({{ model_configurations }}/#land-surface-initial-conditions-sour
edit: `The example experiment focuses on a flood event in Lismore, NSW, using `ERA5-Land` [land-surface initial conditions]({{ model_configurations }}/#land-surface-initial-conditions-source), where the configuration is specified in the [Nesting configuration]({{ model_configurations }}/#nesting-configuration).`

2025-03-28 01:39 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +All {{model}} configurations are and available on MOSRS, through the links at the top of this page.
edit: `All {{model}} configurations are and available on MOSRS via links at the top of this page.`

2025-03-28 01:43 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +- **Start a new [_persistent session_](https://opus.nci.org.au/display/Help/Persistent+Sessions)**<br>
I would remove the line break `<br>` mid sentence.

2025-03-28 01:45 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    For further instructions on assigning the target _persistent session_, refer to the [detailed guide](#specify-target-persistent-session).
edit: Be consistent with`Detailed` of `detailed` guide. Both instances are used throughout. I would go with the proper noun `Detailed guide`

2025-03-28 01:51 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +By completing the [_Cylc_ setup](#cylc), also _Rose_ will be automatically available. Therefore, there is no additional step required.
edit: `By completing the [_Cylc_ setup](#cylc), _Rose_ will also be automatically available. Hence, no additional step required.`

2025-03-28 01:52 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    This step needs to be done once for each new session (e.g.: _Gadi_ login, _ARE_ terminal window)
edit: `... each new session (e.g., _Gadi_ login, _ARE_ terminal window)`

2025-03-28 01:53 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +{{ model }} is comprised of 2 different suites: a [Regional Ancillary Suite (RAS)](#ras) and a [Regional Nesting Suite (RNS)](#rns).
edit: `... {{ model }} comprises two different suites: ...`

2025-03-28 01:55 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +Each {{ model }} suite has a `suite-ID` in the format `u-<suite-name>`, where `<suite-name>` is a unique identifier.<br>
edit: `Both of the suites within {{ model }} have a `suite-ID` in the format ...`

2025-03-28 01:56 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +Typically, an existing suite is copied and then edited as needed for a particular run.
edit: replace `run` with `experiement'

2025-03-28 02:02 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    Many of the steps that follow are to be repeated almost identically for the RAS and RNS. For this reason, details on these steps will be provided only within the RAS section below, whereas in the
edit: `Many of the following steps appear in both the RAS and RNS. For this reason, these steps will be detailed only within the RAS section below, and subsequenltly linked to within the RNS section.`

2025-03-28 02:03 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +The RAS generates a set of ancillary files, such as initial conditions, lateral boundary conditions and forcing conditions, for the domain of interest. These ancillary files are then used by the [RNS
edit: `For the domain of interest, the RAS generates a set of ancillary files, such as initial conditions, lateral boundary conditions and forcing conditions.`

2025-03-28 02:06 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +The RAS configuration can be obtained as a copy of the MOSRS one, following 2 approaches:
edit: `The RAS configuration can be copied from the MOSRS repository via two ways:`

2025-03-28 02:07 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +To create a _local copy_ of the RAS from the UKMO repository, run:
edit: replace `UKMO` with `MOSRS'

2025-03-28 02:09 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +To create a new copy of the RAS both _locally_ and _remotely_ in the UKMO repository, run:
edit: replace `UKMO` with `MOSRS`

2025-03-28 02:09 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +This option is mostly used for testing and examining existing suites.
remove `exisiting` - it's redundant

2025-03-28 02:11 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +When a new suite is created in this way, a _unique_ `<suite-ID>` is generated within the repository and populated with descriptive information about the suite and its initial configuration.
edit: `When a new suite is created in this way, a _unique_ `<suite-ID>` is generated within the MOSRS repository, where you are prompted to add information about the suite and its configuration.`

2025-03-28 02:14 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +When a suite runs, its configuration files are copied on _Gadi_ inside `/scratch/$PROJECT/$USER/cylc-run/<suite-ID>` and a symbolic link to this directory is also created in the `$USER`'s home direct
edit: `When a suite runs, its configuration files are copied in `/scratch/$PROJECT/$USER/cylc-run/<suite-ID>` on _Gadi_. A symbolic link to this directory is also created in the `$USER`'s home directory under `~/cylc-run/<suite-ID>`.`

2025-03-28 02:15 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +To run the RAS, execute the following command from within the [suite directory](#suitedir):
edit: `To run the RAS, execute the following command from within your RAS [suite directory](#suitedir):`

2025-03-28 02:18 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +It is quite common, especially at the beginning, to experience errors and job failures.<br>
edit:`It is not unusual that new users experience errors and job failures.`

2025-03-28 02:21 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +Suite logs are stored in the directory `~/cylc-run/<suite-ID>` within a folder named `log.<TIMESTAMP>`, which is also symlinked as `log` (referred to as _logs folder_ below). Logs from previous runs
edit: `These files can be found in the...`

2025-03-28 02:23 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +??? code "Example of a suite execution log file (click to enlarge)"
edit: `... (click to see contents)`

2025-03-28 02:26 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +For example, the logs for the latest retry of a task named `Lismore_d1000_GAL9_um_recon` at _Cylc_ cycle point `20220226T0000Z` can be in the following folder:
edit: `For example, logs for the most recent retry of a task named `Lismore_d1000_GAL9_um_recon` at Cylc cycle point `20220226T0000Z` can be found in the folder...`

2025-03-28 02:28 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +If your _Cylc_ GUI has been closed and you are unsure whether your suite is still running, you can scan for active suites and reopen the GUI if desired.<br>
remove `if desired`

2025-03-28 02:29 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +In some cases the suite needs to be updated without necessarily having to stop it (e.g., after fixing a typo in a file). Updating an active suite is called a _reload_, where the suite is _re-installe
add comma: `In some cases, the...`

2025-03-28 02:31 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    Cleaning a suite folder will remove any non-archived data (i.e.: output files, logs, executables, etc.) associated with the suite.
edit: `i.e., ` not `i.e.:`

2025-03-28 02:46 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +The ancillaries are divided for each [nested region]({{ model_configurations }}/#nesting), with each of the region subdivided in directories named according to the nests' names. Therefore, the path o
edit: `Ancillaries within a [nested region](https://access-hive.org.au/pr-preview/pr-857/models/configurations/access-ram/#nesting) are separated according to the nest resolution, which are stored in a subdirectories according to the name given to the nest resolution. Thus, the path of ancillaries for a specific nest is...`

2025-03-28 02:52 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +In addition to these nests, a subdirectory named according to the driving model data can be found within the `nested_region_name` directory.<br>
edit: `Similarly, driving model data for each nest resolution can be found within the `nested_region_name` directory.`

2025-03-28 02:59 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +The 2-level (i.e., two nests) example above has one `nested_region_name` called `Lismore`. Driven by ERA5 data, the outer and inner nests are named `d1000` and `d0198`, respectively.<br>
edit: `For the above 2-level nest example, there is one `nested_region_name` called `Lismore`. Driven by ERA5 data, the outer and inner nests (i.e., nest resolution 1 and nest resolution 2) are named `d1000` and `d0198`, respectively.`

2025-03-28 03:00 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +Thus, the ancillary files directory `/scratch/$PROJECT/$USER/cylc-run/<suite-ID>/share/data/ancils/` contains the following folders:
replace 'folders' with 'subdirectories'

2025-03-28 03:05 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +The ancillary data files in output are typically in the [UM fieldsfile](https://code.metoffice.gov.uk/doc/um/latest/papers/umdp_F03.pdf) format.
edit: `Ancillary data files are typically output in the [UM fieldsfile](https://code.metoffice.gov.uk/doc/um/latest/papers/umdp_F03.pdf) format.`

2025-03-28 03:07 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +Steps to obtain and run the RNS configuration, as well as monitoring the logs, are analogous to those listed above for the [RAS](#ras).<br>
edit: `Steps to obtain and run the RNS suite, as well as monitor logs, are similar to those listed above for the [RAS](#ras).<br>`

2025-03-28 03:12 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +To run the RNS configuration, please follow the steps listed in [Run the suite](#run-the-ras).
remove `please`

2025-03-28 03:12 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +To get the RNS configuration, please follow the steps listed in [Get the RAS configuration](#get-the-ras-configuration), making sure you use the correct RNS `suite-ID` `{{ rns_id }}` when copying the
remove `please`

2025-03-28 03:12 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +To check the RNS suite logs, please follow the steps listed in [Check suite logs](#check-suite-logs).
remove `please`

2025-03-28 03:13 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +All the RNS output files are available on _Gadi_ inside the directory `/scratch/$PROJECT/$USER/cylc-run/<suite-ID>`. They are also symlinked in `~/cylc-run/<suite-ID>`.
replace `inside` with `in`

2025-03-28 03:14 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +Within the `cycle` directory, outputs are divided into multiple nested subdirectories in the format `<nested_region_name>/<science_configuration>/<nest_name>`, with [`<nested_region_name>`](#change-t
edit: `The `<science_configuration>` is usually `GAL9` or `RAL3.2`, depending on the [nest resolution]({{ model_configurations }}/#model-components).`

2025-03-28 03:20 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +Therefore, the model output data for the first cycle (`20220226T0000Z`) of the example in this documentation (`Lismore` `nested_region_name`, using a `RAL3P2` `science_configuration` and `d0198` as a
edit: `For example, the model output data for the first cycle (`20220226T0000Z`) of the Lismore experiment (`Lismore` `nested_region_name`, using a `RAL3P2` `science_configuration` and `d0198` as a `nest_name`) can be found in `/scratch/$PROJECT/$USER/cylc-run/<suite-ID>/share/cycle/20220226T0000Z/Lismore/d0198/RAL3P2/um`.`

2025-03-28 03:28 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    To clarify which suite needs editing, each modification paragraph includes a bullet point specifying the relevant suite to edit.
edit: `For each of the following possible modifications, the relevant suite that needs editing is listed as a bullet point.`

2025-03-28 03:29 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    Unless you are a very expert user, directly modifying configuration files is usually discouraged to avoid incurring in errors.
edit: ` Unless you are an experienced user, directly modifying configuration files is usually discouraged to avoid encountering errors.`

2025-03-28 03:30 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    The RNS runs in multiple [PBS jobs][PBS job] submissions, each one constituting a _cycle_. The job scheduler automatically resubmits the suite every chosen _cycling frequency_, until the total _r
remove comma `_cycling frequency_ until`

2025-03-28 03:33 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +        To avoid running the model for longer that desired, we suggest adding `-PT1S` (minus 1 second) to the relative duration specified in the `FINAL_CYCLE_POINT` (related example below).
edit: ` ...(refer to example below).`

2025-03-28 03:34 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    To modify these parameters, within the [Rose GUI](#rosegui) navigate to _suite conf &rarr; Nesting Suite &rarr; Cycling options_, edit the related field and click the _Save_ button ![Save button]
remove comma `To modify these parameters within...`

2025-03-28 03:38 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    For example, to run the experiment for 2 days, starting the 5th April 2000, set `INITIAL_CYCLE_POINT` to `20000405T0000Z` and `FINAL_CYCLE_POINT` to `+P2D-PT1S` (due to the [run length mismatch](
edit: `... for 2 days starting on the 5th April, 2000, set...`

2025-03-28 03:41 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    When changing the land-surface initial conditions source, it is important to always ensure that the nested region's nest configuration aligns with the [nest configuration requirements](#nest-conf
edit: `When changing the land-surface initial conditions source, it is important to ensure that the configuration of the nested region aligns with the [nest configuration requirements](#nest-configuration-requirements).`

2025-03-28 03:43 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +#### Change the simulation region
I would add a bullet point with `RAS and RNS` to be consistent with other "modification paragraphs"

2025-03-28 03:44 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +In {{ model }}, users can perform simulations for distinct regions of Earth by configuring specific parameters for each domain of interest (referred to as _nested region_).<br>
edit: `In {{ model }}, users can perform simulations for a particular region of the Earth by configuring specific parameters for each domain of interest (referred to as _nested region_).<br>`

2025-03-28 03:46 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    To change a nested region name, within the [Rose GUI](#rosegui) navigate to _suite conf &rarr; Regional Ancillary Suite &rarr; Nested region 1 setup_, edit the `rg01_name` field and click the _Sa
edit: break into 2 sentences: `... Edit the...`

2025-03-28 03:47 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    Changing the RAS nested region name changes the [RAS output path](#ras-output-files). As a consequence, the following changes are required within the RNS:
edit: `Consequently, the following...`

2025-03-28 03:48 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +        To change the nested region name, within the [Rose GUI](#rosegui) navigate to _suite conf &rarr; Nesting Suite &rarr; Nested region 1 setup_, edit the `rg01_name` field and click the _Save_ b
edit: break into 2 sentences:` ... Edit the `

2025-03-28 03:48 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    To change the nested region centre, within the [Rose GUI](#rosegui) navigate to _suite conf &rarr; Regional Ancillary Suite &rarr; Nested region 1 setup_, edit the `rg01_centre` field and click t
edit: break into 2 sentences: `... Edit the `

2025-03-28 03:51 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +        To change the first nest ancillary directory, within the [Rose GUI](#rosegui) navigate to _suite conf &rarr; Nesting Suite &rarr; Nested region 1 setup &rarr; Resolution 1 setup_, change the
edit: break into 2 sentences: `... Change the...`

2025-03-28 03:52 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    When changing the nested region position, it is important to always ensure that the nested region's nest configuration aligns with the [nest configuration requirements](#nest-configuration-requir
[pp](edit: When changing the lnested region position, it is important to ensure that the configuration of the nested region aligns with the [nest configuration requirements](#nest-configuration-requirements).)

2025-03-28 04:26 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +Typically, nests within the same nested region are arranged concentrically, with their dimensions and resolutions decreasing towards the innermost nests.
edit: `Typically, nests (resolutions) within the same nested region are arranged concentrically, with increasingly smaller dimensions and higher resolution towards the innermost nests.`

2025-03-28 04:27 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    Currently, {{model}} only supports specific nest configurations, that meet the following criteria:
edit: remove comma `... nest configurations that meet the following criteria:`

2025-03-28 04:31 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    The grid points of the RAS first inner nest (i.e.: _Resolution 2_, because _Resolution 1_ always corresponds to the outer ERA5 domain) need to match the [land-surface initial conditions dataset](
edit: `The grid points of the RAS first inner nest (i.e., _Resolution 2_, because _Resolution 1_ corresponds to the outer ERA5 domain) need to match the ) grid-points of the [land-surface initial conditions dataset]({{model_configurations}}/#land-surface-initial-conditions-source). Therefore, configurations (position, dimension and resolution) for the RAS first inner nest (_Resolution 2_) need to be modified accordingly. Note that the location of the nest is also influenced by the [nested region position](#change-the-nested-region-position).`

2025-03-28 04:32 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +Manually specifying each STASH variable can be complex. To simplify the selection process for commonly used climate analysis variables, predefined groups of STASH variables, known as _stashpacks_, ha
edit: `To simplify the selection process for commonly used climate analysis variables, there are predefined groups of STASH variables known as _stashpacks_.`

2025-03-28 04:33 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    To toggle a _stashpack_, within the [Rose GUI](#rosegui) navigate to _suite conf &rarr; Nesting Suite &rarr; Nested region 1 setup &rarr; Resolution 1 setup &rarr; Config 1 setup_, toggle a speci
edit: break into 2 sentences: `... Toggle a specific...`

2025-03-28 04:34 UTC, heidinett commented on docs/models/run-a-model/run-access-ram.md
> +    For example, to enable stashpack `6` (that includes variables such as wind gust, mean sea level pressure and rainfall amount, for every model timestep) in all nests, set the `6th` button of both
edit: `to enable `stashpack 6`

2025-03-28 04:38 UTC, atteggiani commented on docs/models/run-a-model/run-access-ram.md
> +    The grid points of the RAS first inner nest (i.e.: _Resolution 2_, because _Resolution 1_ always corresponds to the outer ERA5 domain) need to match the [land-surface initial conditions dataset](
@heidinett 
This is the outdated version, would you mind reviewing the updated one please?

2025-03-28 04:40 UTC, heidinett commented on docs/models/configurations/access-ram.md
> +Each of them can contain multiple concentric _nests_, with each nest further refining the resolution of the simulation, allowing for progressively finer detail in areas of interest.
edit: `Each region can contain multiple concentric _nests_, with each nest increasing the resolution of the simulation, allowing for progressively finer detail in areas of interest.`

2025-03-28 04:46 UTC, heidinett commented on docs/models/configurations/access-ram.md
> +Since the regional forecasting is performed separately for each nested region and, within each nested region, is performed for every individual nest, the total computational cost increases with both
edit: `Since the regional forecasting is performed separately for each nested region and for every individual nest within, the total computational cost increases with both the number of nested regions and the number of nests contained within.`

2025-03-28 04:47 UTC, heidinett commented on docs/models/configurations/access-ram.md
> +Similar to the the UKMO Regional Nesting Suite, ACCESS-rAM3 is configured to derive its initial and lateral boundary conditions from the [ECMWF Reanalysis v5 (ERA5)](https://www.ecmwf.int/en/forecast
remove `the` in `Similar to the the UKMO`

2025-03-28 04:48 UTC, heidinett commented on docs/models/configurations/access-ram.md
> +Information about the amount of NCI resources (such as Service Units (SU) and storage) used by a typical ACCESS-rAM3 experiment run are available on the [ACCESS-Hive Forum release notes page](https:/
edit `resources, i.e., Service Units (SU) and storage used ...`

2025-03-28 04:50 UTC, heidinett commented on docs/models/configurations/access-ram.md
> +The structure, horizontal resolution, and placement of [nests](#nesting) can be be customised.<br>
remove comma `resolution and placement`

2025-03-28 04:50 UTC, atteggiani commented on docs/models/configurations/access-ram.md
> +Information about the amount of NCI resources (such as Service Units (SU) and storage) used by a typical ACCESS-rAM3 experiment run are available on the [ACCESS-Hive Forum release notes page](https:/
We might add other types of NCI resources too, so I will keep it as it is.

2025-03-28 06:08 UTC, merged

2025-03-28 06:08 UTC, atteggiani commented
Merged!
Thank you all for your efforts in putting together this documentation.